### ISSUE TITLE
Add Shamir's secret sharing protocol

### ISSUE THREAD

**Issue by tupui** [StellarCN/py-stellar-base#1010]
**Is your feature request related to a problem? Please describe.**

Keeping secrets can be hard and if someone finds the paper wallet, it's compromised.

**Describe the solution you'd like**

I would like to propose to add a helper function to split the secret key using the Shamir protocol. The PyCryptodome library has an implementation we could leverage.

We could propose the following APIs:
```python
Keypair.secret.to_shamir(n, k)
Keypair.from_shamir(...)
```

Of course, naming and input parameters should be worked on.

As usual, I am happy to make a PR if wanted 😃 

**Describe alternatives you've considered**

If not suitable in this library, I will add the feature on my higher level Soroban API library.

**Additional context**

https://pycryptodome.readthedocs.io/en/latest/src/protocol/ss.html

**Comment by overcat** [comment]
Hi @tupui, this is a very good proposal, but I suggest we build this feature based on [python-shamir-mnemonic](https://github.com/trezor/python-shamir-mnemonic). I think we can trust the implementation provided by Trezor. We just need to add two functions: `generate_shamir_mnemonic_phrase` and `from_shamir_mnemonic_phrase`

**Comment by overcat** [comment]
> Keeping secrets can be hard and if someone finds the paper wallet, it's compromised.

In addition, for the existing plan, I strongly recommend adding an extra passphrase (aka. 25th word) and memorizing it, which can alleviate this concern to some extent.

**Comment by tupui** [comment]
Awesome, I can take a shot at it if you want 😃 

I like the 25 words hack. Wondering if this should get into the API in a way or not. But that's another discussion.

**Comment by overcat** [comment]
Hi @tupui, The 25th word is not hack; it is something from the BIP-39 standard, so we have already included support for it, please check https://github.com/StellarCN/py-stellar-base/tree/c5d656f13e63c4049e5cd6c81f396541b96c9833/stellar_sdk/keypair.py#L241-L242

SLIP-39 also has a similar concept, so if you are willing to add SLIP-39 support to this SDK, please also include support for passphrase.

**Comment by tupui** [comment]
I had a Quick Look at the Trezor repo and I two thing caught my eyes:

1. There is not much activity on the repo (vs pycryptodome)
2. They have a disclaimer saying this should not be used in prod

Now I am not sure how much we should be concerned about that. Do you have some thoughts there?

**Comment by overcat** [comment]
Hi @tupui, I personally prefer using the Trezor library; I believe the risks involved are acceptable, but I suggest configuring this feature as an optional one.

Of course, I don't oppose implementing this feature based on pycryptodome, but if you want to do it using pycryptodome, I recommend creating a brand-new Python package that implements SLIP-39 using pycryptodome, and then we can introduce this package into the SDK. What do you think? This way, other users can also more easily use this new package. However, I estimate that this will require a considerable amount of effort.
