### ISSUE TITLE
pip installing not exactly working

### ISSUE THREAD

**Issue by Jaykingamez** [StellarCN/py-stellar-base#109]
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -Isrc/ed25519-supercop-ref -Id:include -Id:include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /Tcsrc/ed25519-glue/ed25519module.c /Fobuild\temp.win-amd64-3.6\Release\src/ed25519-glue/ed25519module.obj
    error: command 'cl.exe' failed: No such file or directory

tried pip installing it, got this.

Command "d:\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\HP\\AppData\\Local\\Temp\\pip-install-1x6uuvav\\ed25519\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\HP\AppData\Local\Temp\pip-record-6__rcqcx\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\HP\AppData\Local\Temp\pip-install-1x6uuvav\ed25519\

**Comment by bolshoy** [comment]
@Jaykingamez some of the dependencies need to be compiled, and looks like you lack a C compiler. Please check for more info here: https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed

**Comment by tempofr** [comment]
Did you try anaconda?
