### ISSUE TITLE
Exception when importing XDR with set_opts that adds a preAuthTx signer

### ISSUE THREAD

**Issue by israellevin** [StellarCN/py-stellar-base#113]
When calling `builder.import_from_xdr` on an XDR that contains a `set_opts` transaction which adds a `preAuthTx` signer, I get the following exception:
```
Exception: Must be a valid strkey if not give signer_type
```
I did specify signer_type, of course.

**Comment by israellevin** [comment]
The problem appears to be a typo in the `SetOptions` class, defining `signer_type` as `Signer_type` with a capital S. See #114 for a fix.

**Comment by overcat** [comment]
Merged, thanks.
