### ISSUE TITLE
How to create a listener by horizon.account_payments ?

### ISSUE THREAD

**Issue by congnghiakhiem** [StellarCN/py-stellar-base#129]
I tried use js-sdk. But it only work with my own horizon. It doesn't work if I change to the live horizon. Therefore I wanna try to use py-stellar to create a listener.
I found that there is horizon.account_payments. But I don't know how to use it.
Can anyone help me to write an example with horizon.account_payments.
Thanks a lot!

**Comment by overcat** [comment]
Please install from the latest code(may be unstable)
```pip install git+git://github.com/StellarCN/py-stellar-base```

Python Version:
```py
from stellar_base.address import Address
addr = Address(address='YOUR STELLAR ACCOUNT', horizon='https://horizon.stellar.org')
payments = addr.payments(sse=True)
for payment in payments:
    print(payment)
```

JS Version:
```js
const StellarSdk = require("stellar-sdk")
const server = new StellarSdk.Server('https://horizon.stellar.org');

const accountAddress = 'YOUR STELLAR ACCOUNT'
const pmHandler = function (pmResponse) {
    console.log(Response);
};

const es = server.payments()
    .forAccount(accountAddress)
    .stream({
        onmessage: pmHandler
    })
```

**Comment by congnghiakhiem** [comment]
Thank you ^^

**Comment by trungnq1510** [comment]
@overcat How can this example work?
Horizon using this code `messages = SSEClient(url)` to init a SSEClient but the SSEClient object's init func required session and build headers. `class SSEClient(object):
    def __init__(self, url, session, build_headers, last_id=None, retry=3000, **kwargs):`

**Comment by overcat** [comment]
@trungnq1510 
The example is written for the v0.2 version.
see: https://github.com/StellarCN/py-stellar-base/blob/v0.2/stellar_base/horizon.py#L172
