### ISSUE TITLE
[Proposal] Provide proper kwargs for Operations

### ISSUE THREAD

**Issue by paultiplady** [StellarCN/py-stellar-base#130]
As a user of this package, while ramping up on Stellar in general I found it quite tedious to construct Operations; instead of writing:

```
operation.AllowTrust({
    'asset_code': asset.code,
    'trustor': beneficiary.address().decode(),
    'authorize': True,
})
```
it would be much more ergonomic and user-friendly to be able to say:

```
operation.AllowTrust(
    asset_code=asset.code,
    trustor=beneficiary.address().decode(),
    authorize=True,
)
```

In the latter case my IDE would give me hints if I'm missing a mandatory argument, and I could use code completion on the kwargs.

Any interest in taking a PR to add kwargs to `Operations` somehow? I can think of a few potential designs depending on whether backwards-compatibility is a requirement, but want to assess interest in upstreaming such a change before embarking on anything.

**Comment by overcat** [comment]
a21de65653e16be68a2eb32678cd4c66291c4b6a
