### ISSUE TITLE
envelope_xdr not decoding from XDR

### ISSUE THREAD

**Issue by skinderis** [StellarCN/py-stellar-base#134]
Hi,

I noticed that I can't decode from xdr string (which I get from transaction).

 ```
       envelope_xdr = tx.get('envelope_xdr')
       te = TransactionEnvelope.from_xdr(envelope_xdr)
```
envelope_xdr is `'AAAAAB0Y5B0+dzkuymcBvFeg83RYv5gNZALXsp4sYd/ju0gxAAAAZACbbl0AAAABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAEjEyMzQ1Njc4OTBzZHNkZjEyMwAAAAAAAQAAAAEAAAAAHRjkHT53OS7KZwG8V6DzdFi/mA1kAteynixh3+O7SDEAAAABAAAAAFwfwXA3LqHloLvczd9lMdmvF/dh0RVJ2LyxZ9cp0ueuAAAAAAAAAABJUE+AAAAAAAAAAAHju0gxAAAAQNchibh2qxL3CBjcpLh0AsT6N4Rfe9LXwzaPJkXEFxLvlyid50jAMgZvblbKEF3IWUjcmjPeh0P9xHxygwxHzgI='`

I get this error:
```
/usr/local/lib/python3.6/site-packages/stellar_base/transaction_envelope.py in from_xdr(cls, xdr)
     70         signatures = te_xdr_object.signatures
     71         tx_xdr_object = te_xdr_object.tx
---> 72         tx = Transaction.from_xdr_object(tx_xdr_object)
     73         te = TransactionEnvelope(tx, {'signatures': signatures})
     74         # te = TransactionEnvelope(tx, {'signatures': signatures, 'network_id': 'PUBLIC'})

/usr/local/lib/python3.6/site-packages/stellar_base/transaction.py in from_xdr_object(cls, tx_xdr_object)
     58         memo_switch = tx_xdr_object.memo.switch
     59         if memo_type == Xdr.const.MEMO_TEXT:
---> 60             memo = TextMemo(memo_switch)
     61         elif memo_type == Xdr.const.MEMO_ID:
     62             memo = IdMemo(memo_switch)

/usr/local/lib/python3.6/site-packages/stellar_base/memo.py in __init__(self, text)
     36     def __init__(self, text):
     37         if not isinstance(text, (str, unicode)):
---> 38             raise TypeError('Expects string type got a ' + type(text).__name__)
     39         if bytes == str and not isinstance(text, unicode):  # Python 2 without unicode string
     40             self.text = text

TypeError: Expects string type got a bytes
```

**Comment by skinderis** [comment]
Is there any solution for that? What I am missing? Thanks!

**Comment by Richard-YAN** [comment]
Seems the issue is still there. Couldn't execute unpack_TransactionEnvelope(), got 

xdrlib.Error: value=2 not in enum PublicKeyType

```
transaction =  server.transactions() \
        .transaction("732149cc8949a14c353c07f34e671bb3313bc9162c99ce64379f857811585d5e").call()
    print(transaction["envelope_xdr"])

xdr_decoded = base64.b64decode(transaction["envelope_xdr"])
    te = Xdr.StellarXDRUnpacker(xdr_decoded)
    te_xdr_object = te.unpack_TransactionEnvelope()
```

**Comment by overcat** [comment]
Hi @Richard-YAN, which version of SDK are you using? I tested it with the latest version (`pip install stellar-sdk==2.10.0`) and found that everything works well.

**Comment by Richard-YAN** [comment]
Hi @overcat, I am using stellar-sdk==2.10.0 too in requirements.txt file for my project with Pycharm IDE. The issue is persistent. 

But the interesting thing is I just tried to use the command (`pip install stellar-sdk==2.10.0`) you gave to install the lib, and execute the code via python terminal, it works.

**Comment by overcat** [comment]
Hi @Richard-YAN, would you mind running the following code in your PyCharm? And copy the output here.
```
try:
    from pip._internal.operations import freeze
except ImportError:  # pip < 10.0
    from pip.operations import freeze

deps = freeze.freeze()
for dep in deps:
    print(dep)
```

**Comment by Richard-YAN** [comment]
I paste some of the output here.  I can see stellar-base and stellar-sdk both are there. 

`
...
SQLAlchemy==1.3.13
sseclient==0.0.27
stellar-base==1.1.2.0
stellar-base-sseclient==0.0.21
stellar-sdk==2.10.0
tinycss2==1.0.2
toml==0.10.0
...
`

**Comment by overcat** [comment]
@Richard-YAN **stellar-base** has been deprecated for a long time, please uninstall it, after that everything should work normally.

**Comment by Richard-YAN** [comment]
Many thanks @overcat ! That's the root cause, it works very well now!
