### ISSUE TITLE
Got "tx_bad_seq" with builder.append_create_account_op 

### ISSUE THREAD

**Issue by congnghiakhiem** [StellarCN/py-stellar-base#141]
`
builder = Builder(secret=mysecret, horizon=myhorizon)

sm = StellarMnemonic("english")

m = sm.generate()

kp = Keypair.deterministic(m, lang='english')

builder.append_create_account_op(

    destination = mydestination,

    starting_balance = config.init_amount

)

builder.sign()

builder.submit()
`

I create new account by this code. It took about 5 seconds for one creating action. But if user A is waiting for new address and user B call to generate new address, then user B will get transaction_failed: tx_bad_seq
I found that problem is the transaction sequence number.
But I don't have ideal to fix it. Please help.

**Comment by overcat** [comment]
Hi, this is not a bug, you need to deal with the problem yourself. You can try to put multiple create account actions in one transaction or or try the consumer producer model.

**Comment by congnghiakhiem** [comment]
Thank you. I tried to use Rabbitmq to process this.
