### ISSUE TITLE
asset_code or asset_type as arg in Builder.append_payment_op()

### ISSUE THREAD

**Issue by ilrico** [StellarCN/py-stellar-base#142]
hello, if we pip "stable", ie from pypi not github then in the github main page exemple "A simple exemple" is not valid.
In Builder.append_payment_op() one should still use asset_type='XLM' instead asset_code='XLM' as indicated.
Maybe would be best wait for pypi update before changing this most read exemple.

**Comment by overcat** [comment]
Sorry, but I don't have control of pypi.
