### ISSUE TITLE
TypeError in call to `ledgers`

### ISSUE THREAD

**Issue by mgraczyk** [StellarCN/py-stellar-base#143]
Calls to `ledgers()` and other methods are broken in `stellar-base==0.1.9.1`

## Steps to Reproduce

```bash
pip install stellar-base==0.1.9.1
python -c 'from stellar_base.horizon import horizon_livenet; print(horizon_livenet().ledgers())'
```

## Expected Results

The call should print a json object representing a Stellar ledger.
This is the behavior in 
`stellar-base==0.1.8.1`

## Actual Results

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/.../python3.6/site-packages/stellar_base/horizon.py", line 357, in ledgers
    return self._get(endpoint, params=params, sse=sse, **kwargs)
  File "/.../python3.6/site-packages/stellar_base/horizon.py", line 79, in _get
    return self._request('GET', endpoint, **kwargs)
  File "/.../python3.6/site-packages/stellar_base/horizon.py", line 67, in _request
    verb, url, timeout=self.timeout, **kwargs)
TypeError: request() got an unexpected keyword argument 'sse'
```

This issue prevents me from using `stellar-base==0.1.9.1` in any capacity.

**Comment by overcat** [comment]
I am sorry about this. I submitted a fix, can you try it?
Install it with `pip install git+git://github.com/StellarCN/py-stellar-base.git@0.1.9`

**Comment by mgraczyk** [comment]
That change fixes this bug.

**Comment by overcat** [comment]
Thank you for your feedback.
