### ISSUE TITLE
UnicodeDecodeError on ManageData

### ISSUE THREAD

**Issue by gpip** [StellarCN/py-stellar-base#144]
Transaction `f436273134cf292ee3d292fc12b5d74697d6c2208b665bdca796ba15bdf737ec` (testnet) has a transaction envelope that results in an exception when attempting to decode it:

```
stellar_base/operation.py", line 1007, in from_xdr_object
    data_value = op_xdr_object.body.manageDataOp.dataValue[0].decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Installed stellar-base using pip, stellar-base==0.1.9.1, python 3.6.4

```
TransactionEnvelope.from_xdr('AAAAAClQlewu0LC19G4iqHhOAMkFiKe34FpxoW80I5whL6qsAAAAZACmIY8AAAACAAAAAAAAAAAAAAABAAAAAAAAAAoAAAAEMjBLQgAAAAEAAABA/wAAAAAAAAAUW5lDX/////8AAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIS+qrAAAAEDyjfg9bnV2H9GpR96LmDizLuieHguNSN3FTG7M/YDzs02ZBL8WhjWeS0Mf8ni+gwYAqWmgf3+dpjAOKcb3THQN')
```

**Comment by overcat** [comment]
Hello, I have submitted a fix for this bug, please help me test this and then tell me the result of your test. 
Install the fix with the command: `pip install git+git://github.com/StellarCN/py-stellar-base.git@5e6576547f560d7c3e5cb9fa9a4ddca47c72aa89`

Thank you.

**Comment by gpip** [comment]
Thank you, it works for me with that fix 👍

**Comment by overcat** [comment]
Thank you for your feedback.
