### ISSUE TITLE
addr.get() return None

### ISSUE THREAD

**Issue by congnghiakhiem** [StellarCN/py-stellar-base#151]
address = 'GDKB...BCFD'
horizon = 'https://horizon.stellar.org'
addr = Address(address=address, horizon=horizon)
print(addr.get())

--> None

**Comment by overcat** [comment]
Please read https://stellar-base.readthedocs.io/en/latest/quickstart.html#looking-up-account-details-on-horizon

**Comment by congnghiakhiem** [comment]
from stellar_base.address import Address
publickey = 'GDVDKQFP665JAO7A2LSHNLQIUNYNAAIGJ6FYJVMG4DT3YJQQJSRBLQDG'
address = Address(address=publickey) # See signature for additional args
address.get() # Get the latest information from Horizon

--> None

Please check your document.

**Comment by overcat** [comment]
Please try
```
from stellar_base.address import Address
publickey = 'GDVDKQFP665JAO7A2LSHNLQIUNYNAAIGJ6FYJVMG4DT3YJQQJSRBLQDG'
address = Address(address=publickey) # See signature for additional args
address.get() # Get the latest information from Horizon
print('Balances: {}'.format(address.balances))
print('Sequence Number: {}'.format(address.sequence))
print('Flags: {}'.format(address.flags))
print('Signers: {}'.format(address.signers))
print('Data: {}'.format(address.data))
```
Maybe I should return the instance?

**Comment by congnghiakhiem** [comment]
I have read the source code for stellar_base.address. It is not necessary to return the instance.

**Comment by overcat** [comment]
Yes, it just made changes on the original instance, please close the issue if there are no more problems.
