### ISSUE TITLE
Mixup on what amounts one should pass

### ISSUE THREAD

**Issue by shredding** [StellarCN/py-stellar-base#153]
Most operations assume an int64-valid integer as input when it comes to amounts. And that is pretty good, as i can do calculations with `Decimal`,  do a `.quantize(Decimal('0.0000001')` and put it into an `Operation.to_xdr_amount`.

However, `append_create_account_op` expects me to give a string and the `to_xdr_amount` is done internally.

Is that by accident or is it for a deeper truth?

Great project, btw, love it.

**Comment by overcat** [comment]
Builder exists to make the sdk easier to use, I use str to prevent the float number from losing precision. [Operation.to_xdr_amount](https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/operation.py#L70) will convert the str amount to the right int64 number.

**Comment by shredding** [comment]
I know, but the other operations, e.g. `append_payment_op` expect the already converted int64, hence I thought this may be accidentally different.

**Comment by overcat** [comment]
CreateAccount and Payment handle the str amount in the same way, they are no different.
CreateAccount: https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/operation.py#L204
Payment: https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/operation.py#L268

If you want to pay 10.25 XLM to bob:
`builder.append_payment_op(destination=bob_address, amount='10.25', asset_code='XLM')`

The sdk will convert the str amount to an int64-valid integer, all operations in the Builder do not require you to handle the conversion.

**Comment by shredding** [comment]
You are right, i had a bug in my code. Sorry for the inconvenience.
