### ISSUE TITLE
Cant install stellar-base:0.1.9.4 on python 2

### ISSUE THREAD

**Issue by Ronserruya** [StellarCN/py-stellar-base#156]
The latest version on PyPi is https://pypi.org/project/stellar-base/0.1.9.4/

The setup.py file has the line
```with open(path.join(this_directory, 'README.md'), encoding='utf-8') as f:```

This fails for python 2 for:  
    ```TypeError: 'encoding' is an invalid keyword argument for this function```.

However I can't even find this code in this repo, is this not an official release? What version should I get from PyPi?

**Comment by overcat** [comment]
https://github.com/StellarCN/py-stellar-base/blob/v0.1/setup.py#L6

I am sorry for that, you can simply remove the two lines and the fix will be released later. Also highly recommended using Python3.

**Comment by overcat** [comment]
I create a new pypi repo(https://pypi.org/project/stellar-sdk/), I will maintain this repo in the future, you can use it.
`pip install stellar-sdk==0.2.1`

**Comment by Ronserruya** [comment]
Got it, thank you!

**Comment by Ronserruya** [comment]
Is there any doc that lists the changes between stellar-base-v1>v2? I see that the release notes state that they are not compatible with one another, so Id like to know if upgrading is worth the effort of fixing compatibility issues
