### ISSUE TITLE
Make PyPI package description readable

### ISSUE THREAD

**Issue by Mattwmaster58** [StellarCN/py-stellar-base#159]
See: https://packaging.python.org/guides/making-a-pypi-friendly-readme/

**Comment by overcat** [comment]
fixed in v0.2.x 
https://pypi.org/project/stellar-sdk/

**Comment by Mattwmaster58** [comment]
Could we show a deprecation warning (or even delete) the stellar-base package to avoid future confusion?

**Comment by overcat** [comment]
@Mattwmaster58 Thanks for your advice, I will pay attention to the aspect in the future.
