### ISSUE TITLE
Address should accept bytes for the address

### ISSUE THREAD

**Issue by skirsch** [StellarCN/py-stellar-base#166]
generate keypair returns bytes. 

I think address should look at k and do a .decode() if it is bytes. Otherwise, a.get() will fail later in an odd way. 

I've run into this more than once. all the other calls take bytes just fine for an address. this one doesn't.

>>> k='GDQLG6DJBBIUV4KVIT6IDERVIBTI7QV5O7S2O523MRJ5CCVY5QXYXBAK'
>>> a=Address(k, network=network, horizon=horizon)
>>> a.get()
>>> k=b'GDQLG6DJBBIUV4KVIT6IDERVIBTI7QV5O7S2O523MRJ5CCVY5QXYXBAK'
>>> a=Address(k, network=network, horizon=horizon)
>>> a.get()
Traceback (most recent call last):
  File "<pyshell#31>", line 1, in <module>
    a.get()
  File "C:\Users\stk\AppData\Local\Programs\Python\Python37-32\lib\site-packages\stellar_base\address.py", line 102, in get
    raise Exception(acc.get('detail'))
Exception: The request you sent was invalid in some way
>>>

**Comment by overcat** [comment]
This issue has been fixed in the v0.2 branch, thank you for your feedback.
