### ISSUE TITLE
Review numpy dependency

### ISSUE THREAD

**Issue by gpip** [StellarCN/py-stellar-base#168]
I was just checking the latest release, congrats on getting to v1. But, isn't the numpy dependency a bit overkill? Wasn't the previous to_xrd_price good enough and was it absolutely necessary to introduce numpy to handle it?

**Comment by overcat** [comment]
Hi, thanks for your feedback, I will try to refactor this function to see how the new function performs, then try to remove numpy.

**Comment by shredding** [comment]
It yields this on my env: `RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88`

**Comment by overcat** [comment]
https://github.com/numpy/numpy/issues/11628

**Comment by tillkolter** [comment]
@overcat The latest `stellar-base` still has the numpy dependency.
