### ISSUE TITLE
Error installing the SDK

### ISSUE THREAD

**Issue by klosor** [StellarCN/py-stellar-base#173]
I get the following error when i do pip install stellarsdk help?

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/3l/4wbt3qtj3ndf36cjg8gsmzxh0000gr/T/pip-install-RT1m87/crc16/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/3l/4wbt3qtj3ndf36cjg8gsmzxh0000gr/T/pip-record-1RC3NK/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/3l/4wbt3qtj3ndf36cjg8gsmzxh0000gr/T/pip-install-RT1m87/crc16/

**Comment by overcat** [comment]
The CRC16 module requires GCC, so install it first. If you are using Ubuntu please run `sudo apt-get install gcc`
