### ISSUE TITLE
stellar update receive transaction

### ISSUE THREAD

**Issue by Gillian217** [StellarCN/py-stellar-base#174]
Hi, Good day

I'm currently working with stellar-core and stellar horizon using py-stellar-base/ sdk. Just want to ask if there's a web socket or a function that can update or notify when receiving new transactions.

Hope you can help me.

**Comment by overcat** [comment]
Horizon uses [SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) to send data, if you want to listen this data, I highly recommend you host the Horizon yourself in production.

Listen transactions
Docs: https://stellar-base.readthedocs.io/en/master/api.html#stellar_base.horizon.Horizon.transactions
```
from stellar_base.horizon import Horizon

horizon = Horizon("https://horizon.stellar.org")
transactions = horizon.transactions(cursor='now', sse=True)
for transaction in transactions:
    print(transaction)
```

Another demo: https://github.com/StellarCN/py-stellar-base/blob/master/examples/listen_payments.py

**Comment by Gillian217** [comment]
Hi @overcat,
thank you for the response, i've tried the code.
1. I set up a stellar node/ horizon 
![screenshot from 2019-01-14 16-40-26](https://user-images.githubusercontent.com/37716672/51102754-24143b00-181b-11e9-8219-d400b91b4406.png)
2. generated an address and run the script.
![screenshot from 2019-01-14 16-37-30](https://user-images.githubusercontent.com/37716672/51102773-3b532880-181b-11e9-9cd4-65bcd3924673.png)
3. funded the account in https://www.stellar.org/laboratory/#account-creator?network=test
![screenshot from 2019-01-14 16-37-39](https://user-images.githubusercontent.com/37716672/51102803-52921600-181b-11e9-9872-32ba95334d8c.png)
but it doesn't show any transaction.

I've also tried the demo on https://github.com/StellarCN/py-stellar-base/blob/master/examples/listen_payments.py
but it only shows 
![screenshot from 2019-01-14 16-33-49](https://user-images.githubusercontent.com/37716672/51102847-7ce3d380-181b-11e9-87b8-a1d2411bd403.png)
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 42
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 43
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 44
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 45
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 46
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 47
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 48
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 49
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 50
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 51
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
/home/gillian/.local/lib/python3.6/site-packages/sseclient.py:64: UserWarning: Connect failed, retry attempt 52
  warnings.warn('Connect failed, retry attempt {}'.format(retry_count))
"hello"
rate limit exceeded


Hope you can help me.

**Comment by overcat** [comment]
![image](https://user-images.githubusercontent.com/2368403/51104218-76a42600-1820-11e9-9389-b06fd47620f1.png)
It looks like your local node is not fully synchronizing the data yet, so you should wait for it to sync up.
In addition, you can configure `PER_HOUR_RATE_LIMIT` for your horizon.

**Comment by Gillian217** [comment]
Hi @overcat 
I've already change the PER_HOUR_RATE_LIMIT from 72000 to 3600 and the node is running for almost 2 days but the syncing of block didn't move.
core_latest_ledger is updating but the history_latest _ledger is still the same.
![screenshot from 2019-01-16 16-17-03](https://user-images.githubusercontent.com/37716672/51235358-3bcdf980-19aa-11e9-99f4-03bf07264a7d.png)

Hope you can help me.

**Comment by overcat** [comment]
It looks like your horizon is not working properly, please check the log of
it. In addition, you need to set PER_HOUR_RATE_LIMIT larger instead of
smaller.

Gillian217 <notifications@github.com> 于 2019年1月16日周三 16:18写道：

**Comment by overcat** [comment]
The article may help you: https://www.stellar.org/developers/software/known-issues.html

You can also try to run the software in Docker.

**Comment by manran** [comment]
@overcat maybe we can omit the connection/disconnect handshake messages.
@Gillian217 use the official testnet horizon instead of your own at this moment.

**Comment by Gillian217** [comment]
Thank you for your help @overcat  and @manran
