### ISSUE TITLE
SDK needs to be updated to handle Horizon 0.17.0 breaking changes 

### ISSUE THREAD

**Issue by ire-and-curses** [StellarCN/py-stellar-base#181]
In Horizon release 0.17.0 (released 26 Feb 2019), several breaking changes were made ([changelog](https://github.com/stellar/go/releases/tag/horizon-v0.17.0)), changing or removing fields that had previously been marked as deprecated.

> Breaking changes
> 
>     Fields removed in this version:
>         Root > protocol_version, use current_protocol_version and core_supported_protocol_version.
>         Ledger > transaction_count, use successful_transaction_count and failed_transaction_count.
>         Signer > public_key, use key.
>     This Horizon version no longer supports Core <10.0.0. Horizon can still ingest version <10 ledgers.
>     Error event name during streaming changed to error to follow W3C specification.
> 

Here is the relevant Horizon commit, showing the fields that were changed: https://github.com/stellar/go/commit/575707ed074a5672438b0f2b788f8b38584ef18d

This is an urgent issue! Any code using this SDK to access a Horizon 0.17.0 server (which includes the SDF public horizon instance at https://horizon.stellar.org/) will be broken until the SDK is updated to match the new response fields.

**Comment by overcat** [comment]
#180

**Comment by overcat** [comment]
Thank you for reaching out to us, I've released a [new version](https://pypi.org/project/stellar-sdk/).
