### ISSUE TITLE
Cant seem to get the balance only

### ISSUE THREAD

**Issue by maleekcodes** [StellarCN/py-stellar-base#191]
I have been trying to get only the balance amount through **(address.balances)** but is showing the balance in a list with other information in a dictionary. whenever i try assigning it to a variable or appending or converting to a string it always says None or Null. Please how do i resolve this? to get the balance amount only?

**Comment by overcat** [comment]
https://stellar-base.readthedocs.io/en/master/quickstart.html#basic-information
```
from stellar_base.address import Address
publickey = 'GDVDKQFP665JAO7A2LSHNLQIUNYNAAIGJ6FYJVMG4DT3YJQQJSRBLQDG'
address = Address(address=publickey) # See signature for additional args
address.get() # Get the latest information from Horizon
```
