### ISSUE TITLE
Infinite recursion with deepcopy

### ISSUE THREAD

**Issue by dianalo** [StellarCN/py-stellar-base#192]
In an application of your library I ran into an infinite recursion when deep copying a transaction object. I tried to give some minimal code to trigger it, below. Interestingly it works fine, if the second operation is directly appended to the operations list, i.e. without using `tx.add_operation()`. Just wanted to point it out to you. If you think this issue does not need to be fixed, you can just close it. 👍 

```
#! /usr/bin/python3

import copy

from stellar_base.transaction import Transaction
from stellar_base.operation import ManageData, Payment
from stellar_base.horizon import horizon_testnet
from stellar_base.asset import Asset

horizon = horizon_testnet()

acc_src = "GD37M6BVC75DMG7EO2L4B4WHNEKUETC5TEOAHII73K3X656OHQDATOBL" # example
acc_dest = "GCRNCYJI7FREANRFD4MAD2DHZF2AP6OPCMG43FFAYFL2DLLJRPZ6CQ4V" # example
seq_num = horizon.account(acc_src).get('sequence')

tx = Transaction(acc_src, seq_num)

tx.add_operation(Payment(acc_dest, Asset('XLM'), '1'))

# doesn't work
tx.add_operation(ManageData("key", "data"))

# if second operation is appended like this instead, it strangely works...
# tx.operations.append(ManageData("key", "data"))

tx_cpy = copy.deepcopy(tx)
```

Edit:
Serialization with `pickle` also doesn't work:
```
dump = pickle.dumps(tx)
pickle.loads(dump) # triggers infinite recursion
```

**Comment by overcat** [comment]
Hi @dianalo, thanks for your feedback, @manran and I both think this is a very interesting bug. 
I have submitted a PR, it's a bit hacky([
Visual analysis](http://www.pythontutor.com/visualize.html#code=from%20copy%20import%20deepcopy,%20copy%0Aimport%20pickle%0A%0A%0Aclass%20Message%3A%0A%20%20%20%20def%20__init__%28self,%20msg%29%3A%0A%20%20%20%20%20%20%20%20self.msg%20%3D%20msg%0A%0A%0Aclass%20Test%3A%0A%20%20%20%20def%20__init__%28self,%20msg%29%3A%0A%20%20%20%20%20%20%20%20self.test%20%3D%20'test'%0A%20%20%20%20%20%20%20%20self.message%20%3D%20Message%28msg%29%0A%0A%20%20%20%20def%20__getattr__%28self,%20item%29%3A%0A%20%20%20%20%20%20%20%20if%20item%20%3D%3D%20'__setstate__'%3A%0A%20%20%20%20%20%20%20%20%20%20%20%20raise%20AttributeError%0A%20%20%20%20%20%20%20%20return%20getattr%28self.message,%20item%29%0A%0A%0Aif%20__name__%20%3D%3D%20'__main__'%3A%0A%20%20%20%20t_origin%20%3D%20Test%28%22hello%22%29%0A%20%20%20%20t_copy%20%3D%20copy%28t_origin%29%0A%20%20%20%20t_deepcopy%20%3D%20deepcopy%28t_origin%29%0A&cumulative=false&curInstr=40&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false)), but works, we will improve it later. Once @manran approves the change, I will merge it into the main branch.
