### ISSUE TITLE
Horizon v0.18.0 Compatibility

### ISSUE THREAD

**Issue by theaeolianmachine** [StellarCN/py-stellar-base#199]
With Horizon v0.18.0, the following breaking changes will occur:

- The `manage_offer` endpoint will be renamed to `manage_sell_offer`
- The `create_passive_offer` endpoint will be renamed to `create_passive_sell_offer`.

We suggest for all Stellar SDK maintainers to offer compatibility between `v.0.17.X` type names as well as the new names in `v.0.18.0` in order to make the transition process from `v0.17.X` to `v0.18.0` to go smoother.

Let me know if you have any questions!

**Comment by overcat** [comment]
Thank you for your reminder. I will release a new version after the test network upgrades to the new protocol version.

**Comment by overcat** [comment]
https://github.com/StellarCN/py-stellar-base/blob/master/CHANGELOG.md#version-120
