### ISSUE TITLE
"hello" and "byebye" messages when using sse=True

### ISSUE THREAD

**Issue by xoryouyou** [StellarCN/py-stellar-base#200]
Following the example https://github.com/StellarCN/py-stellar-base/blob/master/examples/listen_payments.py

It sporadically prints  "hello" and "byebye".

These are obviously no valid payments and should not be handed down to the SDK user.

Currently I've added this snippet to simply ignore these entries:

```python

if payment.data == '"hello"' or payment.data == '"byebye"':
  pass
else:
  payment_handler(payment)

````

This code or similar should be added to the `horizon.py` module to filter out these events.

**Comment by overcat** [comment]
Thanks for your suggestion, I will fix this in the next release.
