### ISSUE TITLE
append_change_trust_op limit submits strangely.

### ISSUE THREAD

**Issue by tempofr** [StellarCN/py-stellar-base#205]
append_change_trust_op(asset_issuer=asset_key, asset_code=asset_name,limit=0)
Does not give error that limit needs to be string. 
append_change_trust_op(asset_issuer=asset_key, asset_code=asset_name,limit="0")
Gives error that it should be str (not unicode).
append_change_trust_op(asset_issuer=asset_key, asset_code=asset_name,limit=str("0"))
OK.

Strangely the tx gets submitted to horizon ok without an error
https://horizon.stellar.org/transactions/5cbf0d9f62c719905c1856f8634afe57d878051c1f0e487ab35a0d01683d4b55

**Comment by overcat** [comment]
Thanks, a PR has been submitted.
