### ISSUE TITLE
Horizon v0.18.0 Release Compatibility

### ISSUE THREAD

**Issue by theaeolianmachine** [StellarCN/py-stellar-base#207]
Hey @overcat, we actually pushed back the renames mentioned in #199 to 0.19.0, but wanted to send this your way regarding the other deprecations present — feel free to close if you're already good to go.

# Horizon 0.18.0 Release
Horizon `0.18.0` has been released, which continues additional work for a better integration with Stellar Protocol 11. This release contains breaking changes from `0.17.*`, including a requirement to use Postgres 9.5+, along with various changes, including deprecations, that further support the protocol changes presented in [CAP-0005](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0005.md) and [CAP-0006](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0006.md).

You can find the [official release on Github](https://github.com/stellar/go/releases/tag/horizon-v0.18.0); below are the release notes.

**This issue has been filed as a reminder for compatibility — if your SDK is already compatible, feel free to just respond on the thread and close it out. Thank you, and let me know if you have any questions!**

## Breaking changes
* Horizon requires Postgres 9.5+.
* Removed `paging_token` field from `/accounts/{id}` endpoint.
* Removed `/operation_fee_stats` endpoint. Please use `/fee_stats`.

## Deprecations
* `fee_paid` field on Transaction resource has been deprecated and will be removed in 0.19.0. Two new fields have been added: `max_fee` that defines the maximum fee the source account is willing to pay and `fee_charged` that defines the fee that was actually paid for a transaction. See  [CAP-0005](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0005.md)  for more information.
* The following operation type names have been deprecated: `manage_offer` and `create_passive_offer`. The names will be changed to: `manage_sell_offer` and `create_passive_sell_offer` in 0.19.0.

## Changes
* The following new config parameters were added. When old `max-db-connections` config parameter is set, it has a priority over the the new params. Run `horizon help` for more information.
	* `horizon-db-max-open-connections`
	* `horizon-db-max-idle-connections`
	* `core-db-max-open-connections`
	* `core-db-max-idle-connections`
* Fixed `fee_paid` value in Transaction resource ( [#1358](https://github.com/stellar/go/pull/1358) ).
* Fix `int64: value out of range` errors in trade aggregations ( [#1319](https://github.com/stellar/go/pull/1319) ).
* Improved `horizon db reingest` range command.

**Comment by overcat** [comment]
The latest SDK is compatible with the Horizon 0.18.0.
