### ISSUE TITLE
 Support for SEP 10 challenge transaction

### ISSUE THREAD

**Issue by ire-and-curses** [StellarCN/py-stellar-base#211]
SEP 10 describes a [specific form](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md#response) for the "challenge" transaction used for authentication. Providing a helper at the SDK level makes sense to save users from reimplementing the spec.

Here are example implementations in [Go](https://github.com/stellar/go/pull/1468) and [JS](https://github.com/stellar/js-stellar-sdk/pull/375).

**Comment by overcat** [comment]
I will implement it as soon as possible.

**Comment by overcat** [comment]
Already implemented in v1, the implementation of the v2 version will wait until the alpha version is released.
