### ISSUE TITLE
Combine/serialize xdr and signature 

### ISSUE THREAD

**Issue by d1vo1t** [StellarCN/py-stellar-base#228]
I have the below transaction 
 `AAAAANNSjN1wrdfixw+4w0zmKXvxxikg6EKMi9SW1DnNPhNjAAAAZAAAAAAAAAACAAAAAAAAAAEAAAAHdGVzdGluZwAAAAABAAAAAAAAAAkAAAAAAAAAAc0+E2MAAABA0nGC1i7CxTIJYNZKgo067Tr6JTCZTIU5Jwa2kpNMR7ayPohKVTaO53kojTn0c+NftXaogRZvz4/9etdOhDhlDQ==`

and signature from ledger 
"s9B4TLRtoqrUgqBYh80ktdAKxoX5NHj5EkdN49ohWhU="

how do I combine/serialize these two into a valid final tx, I tried converting the xdr string to TrasnactionEnvlope and add the signature but did not work 

```
b64 = "AAAAANNSjN1wrdfixw+4w0zmKXvxxikg6EKMi9SW1DnNPhNjAAAAZAAAAAAAAAACAAAAAAAAAAEAAAAHdGVzdGluZwAAAAABAAAAAAAAAAkAAAAAAAAAAc0+E2MAAABA0nGC1i7CxTIJYNZKgo067Tr6JTCZTIU5Jwa2kpNMR7ayPohKVTaO53kojTn0c+NftXaogRZvz4/9etdOhDhlDQ=="
resp['signature'] = s9B4TLRtoqrUgqBYh80ktdAKxoX5NHj5EkdN49ohWhU

tx = Transaction.from_xdr_object(b64)
te = TransactionEnvelope(tx, signatures=resp['signature'])
```

What am I doing wrong here ? please advice

**Comment by overcat** [comment]
Hope this example can help you.
```python
from stellar_base import Keypair
from stellar_base.transaction_envelope import TransactionEnvelope

b64 = "AAAAANNSjN1wrdfixw+4w0zmKXvxxikg6EKMi9SW1DnNPhNjAAAAZAAAAAAAAAACAAAAAAAAAAEAAAAHdGVzdGluZwAAAAABAAAAAAAAAAkAAAAAAAAAAc0+E2MAAABA0nGC1i7CxTIJYNZKgo067Tr6JTCZTIU5Jwa2kpNMR7ayPohKVTaO53kojTn0c+NftXaogRZvz4/9etdOhDhlDQ=="
tx = TransactionEnvelope.from_xdr(b64)

# sign with another new keypair
new_kp = Keypair.from_seed('SC3XDN7Q3H7HR7IRMGIYJORYE57WZUJOOD5B3H6TKRY22AGBFY3WSYD6')
tx.sign(new_kp)

new_xdr = tx.xdr()
print(new_xdr.decode())
```

**Comment by d1vo1t** [comment]
ledger -> hardware wallet 
what I did was I passed the transaction envelope into ledger hardware wallet and then it returned a signature ! 

How do I include that signature into the transaction envelop

**Comment by overcat** [comment]
What is the full data returned by Ledger? Do you mind showing it here? I don't have a Ledger, so it's hard to debug it, but `s9B4TLRtoqrUgqBYh80ktdAKxoX5NHj5EkdN49ohWhU` doesn't look like a full signature.

**Comment by d1vo1t** [comment]
Unsigned TX 
`AAAAALPQeEy0baKq1IKgWIfNJLXQCsaF+TR4+RJHTePaIVoVAAAAZAANe5gAAAABAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAj2C/4PiTCADuEXb4hrltqbcz0zBpzuwpsePt2Pfr0PMAAAAAAAAABKgXyAAAAAAAAAAAAA==`

REPLY from ledger 
```
<SignedTx: {'public_key': b'\xb3\xd0xL\xb4m\xa2\xaa\xd4\x82\xa0X\x87\xcd$\xb5\xd0\n\xc6\x85\xf94x\xf9\x12GM\xe3\xda!Z\x15', 'signature': b'\x11\x13<:\xc9\xc4\xa4\xda\n\x0f\x11\x8c\xf9\x7f\xa2bX\x9f\xd3)\xf0\x88\x13y\rE-\xcf\x15g\xb7\xb6\x07j\xb6D|\xbe\x07\xfa\xec\x12`6\xd9\x11s\x07\xe2\xce{@\xd4\xaa=\x12\xa2\xc9\xdc\x05l\x85\xb0\n'}>
```

**Comment by overcat** [comment]
Hi, @d1vo1t, thank you for your assistance, I will improve this process later. The code below is an example, you can give it a try.
```python
import base64
import ed25519

from stellar_base import Keypair
from stellar_base.transaction_envelope import TransactionEnvelope
from stellar_base.stellarxdr import Xdr


def signature_hint_from_raw_public_key(raw_public_key):
    verifying_key = ed25519.VerifyingKey(raw_public_key)
    kp = Keypair(verifying_key)
    return kp.signature_hint()


unsigned_xdr = "AAAAALPQeEy0baKq1IKgWIfNJLXQCsaF+TR4+RJHTePaIVoVAAAAZAANe5gAAAABAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAj2C/4PiTCADuEXb4hrltqbcz0zBpzuwpsePt2Pfr0PMAAAAAAAAABKgXyAAAAAAAAAAAAA=="
ledger_resp = {
    "public_key": b"\xb3\xd0xL\xb4m\xa2\xaa\xd4\x82\xa0X\x87\xcd$\xb5\xd0\n\xc6\x85\xf94x\xf9\x12GM\xe3\xda!Z\x15",
    "signature": b"\x11\x13<:\xc9\xc4\xa4\xda\n\x0f\x11\x8c\xf9\x7f\xa2bX\x9f\xd3)\xf0\x88\x13y\rE-\xcf\x15g\xb7\xb6\x07j\xb6D|\xbe\x07\xfa\xec\x12`6\xd9\x11s\x07\xe2\xce{@\xd4\xaa=\x12\xa2\xc9\xdc\x05l\x85\xb0\n",
}

signature_hint = signature_hint_from_raw_public_key(ledger_resp["public_key"])
decorated_signature = Xdr.types.DecoratedSignature(
    signature_hint, ledger_resp["signature"]
)

te = TransactionEnvelope.from_xdr(unsigned_xdr)
te.signatures.append(decorated_signature)

print(te.xdr())
```

**Comment by manran** [comment]
it works except  `from stellar_base.keypair import Keypair`

**Comment by d1vo1t** [comment]
That worked like magic, I was no where near the solution BTW where can I find information about transaction layout or serialization, what I mean is for bitcoin I know first 4 bytes are version, then next byte indicates the number of inputs and so on 

where can I find this information for stellar  transactions
