### ISSUE TITLE
Get list of transactions of a previously merged account

### ISSUE THREAD

**Issue by madetaille** [StellarCN/py-stellar-base#230]
Hi, 

I am trying to get the list of transactions of a previously merged account. When using those lines : 

```
account = Address(address=merged_account_address, horizon_uri=horizon_uri)
account.get()
```

I then get a 404 error, because I guess the account is no more on the Stellar ledger as it was merged.

However, if I skip the `account.get()`, I managed to get the list of transactions linked to this account. 

What does the line account.get() do exactly? Will I always get the same list of transactions of a target merged account if I do not use it?

Thanks for your help!

**Comment by overcat** [comment]
It actually send an HTTP request to this address(https://horizon.stellar.org/accounts/YOUR_STELLAR_ADDRESS). 

If you try to query an account that has already been merged, you will get a 404 error, but you can use [this tool](https://stellar.expert/explorer/public) to query the merged account.

**Comment by manran** [comment]
Hi,
Horizon will return you the history of  tx and other info  of the account
even it was merged.  This is what the blockchain provides to us.

**Comment by madetaille** [comment]
But it actually works if I do not use the `account.get()` line. I get the right list of transactions of the merged account.

That is why I was asking about what this line was doing.

The line I am using to get the transactions is `account.transactions()`. If I use : 
```
account = Address(address=merged_account_address, horizon_uri=horizon_uri)
account.transactions()
```

I can get the list of transactions of a merged account. One other question I had would be how up to date is this list of transactions ? Do I get the list of all the transactions of the merged account before it was merged ? Will it be always the same result, whatever the node contacted ? 

Thanks.

**Comment by overcat** [comment]
When you call `account.get()`, the SDK will request https://horizon.stellar.org/accounts/YOUR_STELLAR_ADDRESS, which will throw a 404 exception.
When you call `account.transactions()`, the SDK will request https://horizon.stellar.org/accounts/YOUR_STELLAR_ADDRESS/transactions and you can get the list of transactions.

If you are using the [official horizon](https://horizon.stellar.org), you can get all the records. Whether you can get the complete data depends on how much data is synchronized by this horizon. If an horizon does not synchronize enough data, you may not be able to get some early records, but the latest records are generally available.

**Comment by madetaille** [comment]
Ok, got it. It's more clear now. 

Long term speaking, I will then get all the transactions of the merged account.

That's all I wanted to know thank you.

**Comment by overcat** [comment]
Welcome, I'm closing this issue now, if you have other questions, feel free to open another issue.
