### ISSUE TITLE
Documentation should explain contents of types

### ISSUE THREAD

**Issue by msfeldstein** [StellarCN/py-stellar-base#235]
In classes like Address, its unclear what properties such as `balances` `flags` or most other fields actually contain.  For example I'm not sure if `balances` is an array or a dict, and im not sure what properties the values inside of it contain.  It's also unclear if `inflation_destination` is a public key string or an Address type.

Documentation should clarify what the shapes and types of all these properties are so we don't need to guess via trial and error or inspection

https://stellar-base.readthedocs.io/en/latest/_modules/stellar_base/address.html#Address.get

**Comment by overcat** [comment]
We released a new library([stellar-model](https://github.com/StellarCN/stellar-model)), and we may bring it to stellar-sdk later.
