### ISSUE TITLE
Can't submit built transaction to newly not activated address

### ISSUE THREAD

**Issue by skinderis** [StellarCN/py-stellar-base#239]
Trying to use this method (provided in examples of this repo) to built, sign and submit transaction to newly generated keypair:

```
# Alice pay 10.25 XLM to Bob
from stellar_base.builder import Builder

alice_secret = 'SCB6JIZUC3RDHLRGFRTISOUYATKEE63EP7MCHNZNXQMQGZSLZ5CNRTKK'
bob_address = 'GA7YNBW5CBTJZ3ZZOWX3ZNBKD6OE7A7IHUQVWMY62W2ZBG2SGZVOOPVH'

builder = Builder(secret=alice_secret)
builder.add_text_memo("Hello, Stellar!").append_payment_op(
    destination=bob_address, amount='10.25', asset_code='XLM')
builder.sign()
response = builder.submit()
print(response)
```

But get this result_xdr:

` 'result_xdr': 'AAAAAAAAAGT/////AAAAAQAAAAAAAAAB////+wAAAAA='`

If I send 1 lumen from another source, then  I can send XLM to that address.

Stellar base py version: v1.4.0
horizon_version : "v0.23.1",
core_version : "v12.2.0"

Maybe method of sending XLM to newly generated key should be different? @overcat 
Thanks!

**Comment by overcat** [comment]
Please check the document:

For v1.4.0:
https://stellar-base.readthedocs.io/en/1.4.0/quickstart.html#create-an-account

For v2.0.0:
https://stellar-sdk.readthedocs.io/en/2.0.0/create_account.html#using-the-stellar-live-network

Igoris <notifications@github.com> 于 2019年12月2日周一 03:31写道：

**Comment by skinderis** [comment]
Thanks a lot! @overcat
