### ISSUE TITLE
Wrong timeout exception on transaction POST when the network is clogged

### ISSUE THREAD

**Issue by bantalon** [StellarCN/py-stellar-base#250]
**Describe the bug**
According to the [POST transaction documentation](https://www.stellar.org/developers/horizon/reference/endpoints/transactions-create.html#timeout), the server will try to push the transaction into 3 consecutive ledgers before returning a [Horizon timeout error](https://www.stellar.org/developers/horizon/reference/errors/timeout.html). Therefore, the [default timeout of 11 seconds](https://github.com/StellarCN/py-stellar-base/blob/c6c10eab8ad3066a2f1e24681bda9c766a152d84/stellar_sdk/client/aiohttp_client.py#L16) seems not enough.
I got to a situation where I got the following exception instead of the aforementioned one:
```
  File "/app_dir/env/lib/python3.6/site-packages/stellar_sdk/client/aiohttp_client.py", line 102, in post
    response = await self._session.post(url, data=data)
  File "/app_dir/env/lib/python3.6/site-packages/aiohttp/client.py", line 497, in _request
    await resp.start(conn)
  File "/app_dir/env/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 857, in start
    self._continue = None
  File "/app_dir/env/lib/python3.6/site-packages/aiohttp/helpers.py", line 585, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
```
By the way, the transaction did succeed to be pushed to the blockchain: [link](https://stellar.expert/explorer/public/tx/0c80d7a914201937c4cc445853035c234450e49b2cc39591202530504c0540d1).

**What version of dependencies are you using?**
stellar-sdk=2.0.0

**To Reproduce**
It is not easy to reproduce. It requires the network to be clogged, which is pretty rare.

**Expected behavior**
In the sane flow, the method should either fail with [Horizon timeout error](https://www.stellar.org/developers/horizon/reference/errors/timeout.html) or succeed. I believe that for this post request, the timeout should be changed to 16  seconds (3 ledgers + 1 second). I am not sure if such a long timeout is desired for other requests.

**Additional context**
N/A.

**Comment by overcat** [comment]
Hi, thanks for the response, I will do more test later. 
Currently, you can set `request_timeout` to 16 or greater, see https://stellar-sdk.readthedocs.io/en/latest/api.html#stellar_sdk.client.aiohttp_client.AiohttpClient

**Comment by bantalon** [comment]
Yep. I already implemented it on my code as a workaround :)
