### ISSUE TITLE
How to provide additional transaction query params for order and cursor

### ISSUE THREAD

**Issue by AnimusXCASH** [StellarCN/py-stellar-base#273]
In previous API there was a chance to return transactions for account based on order (ascending/descending) and setting cursor limit through paging token. 

Is this still possible or if it is planned to be added back in the future?

Thank you for your time and answer.

brg

Animus

**Comment by overcat** [comment]
Hi, you can find it in [the documentation](https://stellar-sdk.readthedocs.io/en/2.2.1/api.html#stellar_sdk.call_builder.TransactionsCallBuilder.order) and [the example](https://github.com/StellarCN/py-stellar-base/blob/master/examples/query_horizon.py)

Demo for you:
```
from stellar_sdk import Server

server = Server(horizon_url="https://horizon-testnet.stellar.org")

transactions = server.transactions().order(desc=True).limit(5).call()
print(transactions)
```

**Comment by AnimusXCASH** [comment]
Thank you sir for DEMO.
