### ISSUE TITLE
SSEClient  __init__() takes from 2 to 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by srgbsv** [StellarCN/py-stellar-base#310]
**Describe the bug**
When I try to run test example from https://stellar-sdk-zh-cn.readthedocs.io/en/latest/querying_horizon.html with streaming requests, I have got error:

``
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    for batch in payments:
  File "..../lib/python3.7/site-packages/stellar_sdk/client/requests_client.py", line 169, in stream
    params=query_params,
  File "..../lib/python3.7/site-packages/stellar_sdk/client/requests_client.py", line 206, in __init__
    url, last_id, retry, session, chunk_size, connect_retry, **kwargs
TypeError: __init__() takes from 2 to 6 positional arguments but 7 were `given`
``

**What version of dependencies are you using?**
sseclient	0.0.25	
stellar-base	1.1.2.0	
stellar-base-sseclient	0.0.21	
stellar-sdk	2.3.1	

**To Reproduce**
Run this code from https://stellar-sdk-zh-cn.readthedocs.io/en/latest/querying_horizon.html

```
from stellar_sdk import Server  

server = Server(horizon_url="https://horizon-testnet.stellar.org") account_id = "GASOCNHNNLYFNMDJYQ3XFMI7BYHIOCFW3GJEOWRPEGK2TDPGTG2E5EDW" 
last_cursor = 'now'  # or load where you left off   
def tx_handler(tx_response):     
    print(tx_response)   
for tx in server.transactions().for_account(account_id).cursor(last_cursor).stream():     
    tx_handler(tx)
```

**Expected behavior**
Getting account transaction information

**Comment by overcat** [comment]
Please uninstall `sseclient`, it conflicts with `stellar-base-sseclient`. 

I recommend that you use a separate [virtual environment](https://docs.python.org/3/library/venv.html) for each project, and you do not need to install `stellar-base`, it has been deprecated.

https://stellar-sdk.readthedocs.io/en/latest/install.html

**Comment by srgbsv** [comment]
I used virtual environment and the error not reproduced. Thanks a lot!
