### ISSUE TITLE
Typo in fetching previous page 

### ISSUE THREAD

**Issue by KStasi** [StellarCN/py-stellar-base#312]
It checks the wrong ref.
https://github.com/StellarCN/py-stellar-base/blob/c947839431be11571f738f34d8a84452e3f31585/stellar_sdk/call_builder/base_call_builder.py#L148-L150

**Comment by overcat** [comment]
Thank you, fixed in v[2.3.2](https://github.com/StellarCN/py-stellar-base/releases/tag/2.3.2).
