### ISSUE TITLE
Implement join(self, join: str) for PaymentsCallBuilder

### ISSUE THREAD

**Issue by KStasi** [StellarCN/py-stellar-base#321]
**Is your feature request related to a problem? Please describe.**
Native Horizon API allows query option `?join` for payments https://www.stellar.org/developers/horizon/reference/endpoints/payments-for-account.html
This is quite handy because it reduces the number of requests needed to get all information about transactions with payments without fetching unrelated operations.

**Describe the solution you'd like**
Add method for PaymentsCallBuilder similar to https://github.com/StellarCN/py-stellar-base/blob/c571012417e07b3c7864535ea422f2d4c0c4261a/stellar_sdk/call_builder/operations_call_builder.py#L84-L91

**Comment by overcat** [comment]
Thanks for your response, released in [2.5.1](https://github.com/StellarCN/py-stellar-base/releases/tag/2.5.1).
