### ISSUE TITLE
Issues with v2.6.0

### ISSUE THREAD

**Issue by yuriescl** [StellarCN/py-stellar-base#338]
Please see https://github.com/stellar/transfer-server-validator/issues/141

**Comment by overcat** [comment]
Hi @yuriescl, do you mind giving me a feedback? Now that transfer-server-validator has upgraded the JS SDK, can Python SDK v2.6.0 pass all tests?

**Comment by yuriescl** [comment]
@overcat It's all green for testnet.
For pubnet there are a couple of errors in SEP10:

![screenshot](https://user-images.githubusercontent.com/26092447/85093476-c976cf80-b1c2-11ea-92ed-161ea1249f77.png)

**Comment by overcat** [comment]
Is there any other information available for debugging?

**Comment by yuriescl** [comment]
@overcat This is the anchor domain used on that test:
https://k.tempocrypto.com

**Comment by overcat** [comment]
There is a bug in v2.6.0 and previous versions that will cause `SEP10 > signers support > fails if a challenge for a nonexistent account has extra client signatures` to fail. I have fixed this issue in [v2.6.1-alpha1](https://pypi.org/project/stellar-sdk/2.6.1a1/), but this bug does not affect other test cases, so I hope you can check your code and configuration file, looking forward to your reply.

In addition, I configured a SEP-10 server in the production environment, you can use it for testing, anchor name is **overcat.me**

You can install v2.6.1-alpha1 by running `pip install stellar-sdk==2.6.1a1`

**Comment by overcat** [comment]
You can find my auth server demo code here (P.S. the code is very rough)
https://gist.github.com/overcat/341c21f7e4d906a9bb8db042a6e361b6

**Comment by yuriescl** [comment]
@overcat `k.tempocrypto.com`'s SEP-10 code is a replica of [Django Polaris SEP-10](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/sep10/views.py). I compared it to your anchor code and it looks equivalent except for [this line](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/sep10/views.py#L134).
Do you know of any pubnet anchor using Django Polaris?

**Comment by overcat** [comment]
Hi @yuriescl, I built an authorization server with Django Polaris, everything is running very well, I think you have not configured `HORIZON_URI`(or something else) correctly, I suggest that you add breakpoints in [this file](https://github.com/stellar/django-polaris/blob/7cfa8508b14b26f42c5e78fba9feb14f121d43f1/polaris/polaris/settings.py), and then check whether all configurations are correct.
