### ISSUE TITLE
How to retrieve a list of “pending Truslines” to verify?

### ISSUE THREAD

**Issue by farzbood** [StellarCN/py-stellar-base#345]
Assume I have a [Custom Asset] that either or both of it's [Issuer] Account [Authorization required] Flag set to True. How can I fetch a list of [Pending Trustlines] for my [Asset] in each corresponding Account in order to verify at any desired time?
Stay Safe V

**Comment by overcat** [comment]
In general, you should not get these accounts through Horizon. 

Only when you need to verify user information, you will set `Authorization required` to `True`, at this time, users should submit **their accounts** with this verification information, and then you can verify the information and decide whether to give the user authorization.

If you still want to obtain these accounts through Horizon, you can use [the endpoint](https://horizon-testnet.stellar.org/accounts/?asset=Hello%3AGDJKBIYIPBE2NC5XIZX6GCFZHVWFUA7ONMQUOOVTLIM3BESTI4BYADAN), but I do not recommend you to do so.

FYI:
- https://www.stellar.org/developers/horizon/reference/endpoints/accounts.html
- https://stellar-sdk-zh-cn.readthedocs.io/en/latest/api.html#stellar_sdk.call_builder.AccountsCallBuilder.for_asset
```python
from stellar_sdk.asset import Asset
from stellar_sdk.keypair import Keypair
from stellar_sdk.server import Server

server = Server(horizon_url="https://horizon-testnet.stellar.org")

issuing_keypair = Keypair.from_secret(
    "SCBHQEGSNBTT4S7Y73YAF3M3JSVSTSNBGAVU5M4XVFGUF7664EUXQHFU"
)
issuing_public = issuing_keypair.public_key

hello_asset = Asset("Hello", issuing_public)

resp = server.accounts().for_asset(hello_asset).limit(20).call()
```

**Comment by farzbood** [comment]
Hi Jun Lo,
The reason I want to have the list, is that when/if consumers forgot to
inform the Anchor about that Trustline, We (as anchor) be able to check the
pending Trustline(s) and contact them about finalizing the process.
thank you for the reply, it totally solved the case.
Stay Safe

**Comment by overcat** [comment]
I recommend that you read SEP-24, which contains information about KYC.

https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md

Farzin <notifications@github.com> 于2020年7月6日周一 下午4:19写道：

> Hi Jun Lo,
> The reason I want to have the list, is that when/if consumers forgot to
> inform the Anchor about that Trustline, We (as anchor) be able to check the
> pending Trustline(s) and contact them about finalizing the process.
> thank you for the reply, it totally solved the case.
> Stay Safe
>
>

**Comment by farzbood** [comment]
Sure,
Thanks again.
