### ISSUE TITLE
Is there any systematic/Organic tide between Accounts on  the Ledger?

### ISSUE THREAD

**Issue by farzbood** [StellarCN/py-stellar-base#347]
Hi Community,
I wonder if there's an organic relationship between an Account that Creates other Accounts on the Ledger or not?
Assume we have an Institution with a couple of Board Members, each have an Account of their own.
When we attemp to create an Asset and offer it to the public, it's Issuing-Account (with it's own Signer(s), Options e.g. "Weights/Treshholds" etc.) should create with a Source-Account (according to Stellar documentation, any Account needs to be created by  another "Source-Account").
As far I understand, Accounts have no special previledge over other Accounts on the Ledger (Custodial/Hirarchial/...), so is there any difference (from programming/technical perspective) which Account we use as so-called Source-Account for this Operation? or is it just a matter of, let's say our Organizational Structure to decide?
Clarify this for me please.
Stay Safe Ya'll
P.S.
While I was exploring my pilot-app's transactions, this comes across:
Account: "GA263PIIYTCWVD7TQX2TLC7KCHW6EOP5A57ZIOY4OR33GA2SJ2C4EETI" created by
Account: "GAEINH2YYS57QGSR2M4VGU6XSILY3NQLFKVIQN7AJN545HK2UC6NV4SP" based on this query:
https://horizon-testnet.stellar.org/accounts/GA263PIIYTCWVD7TQX2TLC7KCHW6EOP5A57ZIOY4OR33GA2SJ2C4EETI/operations

But the corresponding "create_account" Operation isn't listed in this query for:
Account: "GAEINH2YYS57QGSR2M4VGU6XSILY3NQLFKVIQN7AJN545HK2UC6NV4SP"
https://horizon-testnet.stellar.org/accounts/GAEINH2YYS57QGSR2M4VGU6XSILY3NQLFKVIQN7AJN545HK2UC6NV4SP/operations

Does it make sense?
Worth noting that my other Source-Accounts still hold these entries in their queries for Accounts created until "2020-07-01", but not any newly created Accounts afterward. (Perhaps some updates in the Horizon/Core caused it in the meantime)

**Comment by overcat** [comment]
Let us make an assumption, assuming that a company is created by the communication of Alice, Bob, and David. At this time, they can create a public account to manage the company’s assets. This public account can be created by any person, but the permissions(Signer/Treshholds/Op weight) for public accounts need to be set correctly.

For the second question, you have to understand that `GAEINH2YYS57QGSR2M4VGU6XSILY3NQLFKVIQN7AJN545HK2UC6NV4SP` not raise an operation, it was only passively affected by an operation. You can check the effect of the operation on the account through the following link.
- https://horizon-testnet.stellar.org/accounts/GA263PIIYTCWVD7TQX2TLC7KCHW6EOP5A57ZIOY4OR33GA2SJ2C4EETI/effects
- https://horizon-testnet.stellar.org/accounts/GAEINH2YYS57QGSR2M4VGU6XSILY3NQLFKVIQN7AJN545HK2UC6NV4SP/effects

BTW, for questions that are not directly related to the SDK, you can usually get answers faster and better [here](https://stellar.stackexchange.com/).

Best

**Comment by farzbood** [comment]
Hi Jun,
I already have a profile on [Stellar.stackexchange] and put some questions
up there, but the recent matters, since the "create_account" is an
"type_i=0" [Operation] with the <source_account> set to the "funder"
public_key as you can see it for yourself in the historical data of another
account i used for my test scenarios as follow until a certain date (7
entries - but 8 Accounts created by, one after this date) "2020-07-01", I
wasn't sure if it's because of SDK "OperationsCallBuilder" behaviour or the
Horizon end-point, I won't bother you anymore for such cases anymore.(so
It's a non-announced! change in the "operations end-point" you didn't aware
of that apparently too)
https://stellar-sdk-zh-cn.readthedocs.io/en/latest
https://horizon-testnet.stellar.org/accounts/GDP4HJRNBGEX5QCMJ7L54HYCIBRXH6IR6VUZ5HWBOLUPMALRKV4N2HHY/operations

By the SDK definition, " This endpoint represents all operations that were
included in valid transactions that affected a particular account"
https://stellar-sdk-zh-cn.readthedocs.io/en/latest/api.html?highlight=_set_options_op#stellar_sdk.call_builder.OperationsCallBuilder.for_account
and the "create_account" operation affects "source_account" since it
"funds"/"pay" the destination/created Account. so you see it's not that
irrelevant to the SDK though.(it's methods outcome changed!)

Even the "EffectsCallBuilder" may expose the same data, but what if a
developer used some documented working method in his/her app and it changes
without notice in future, that app would misbehave! (not so promising) :/

Let's wrap it up, for what I understand, there's no dependencies on
Accounts (Except for an <Asset> to its <Issuer>)
and we have to opt-in what path we choose, based on our internal policies,
right?

Hopefully we have productive/constructive chats in the future.
All the best.

**Comment by overcat** [comment]
I misunderstood it, I am sorry for the confusion.

The documentation is correct, you can find this **create_account** operation in the two accounts.

- https://horizon-testnet.stellar.org/accounts/GA263PIIYTCWVD7TQX2TLC7KCHW6EOP5A57ZIOY4OR33GA2SJ2C4EETI/operations

- https://horizon-testnet.stellar.org/accounts/GAEINH2YYS57QGSR2M4VGU6XSILY3NQLFKVIQN7AJN545HK2UC6NV4SP/operations?cursor=4482386783899649&limit=200&order=asc

Because each page has a query entry limit, you need to set the cursor and limit. See: https://www.stellar.org/developers/horizon/reference/endpoints/operations-for-account.html

Please allow me to say sorry again.

**Comment by farzbood** [comment]
All good.
Thanks a lot.
Best of All
