### ISSUE TITLE
running sample in ubuntu 15.10

### ISSUE THREAD

**Issue by jobforp** [StellarCN/py-stellar-base#35]
Installed via setup.py on ubuntu 15.10

Traceback (most recent call last):
  File "./sample.py", line 53, in <module>
    operation,
  File "build/bdist.linux-x86_64/egg/stellar_base/transaction.py", line 24, in __init__
AssertionError

-------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-64-1f2b12521563> in <module>()
      7                 'fee': 100,
      8 		'operations': [
----> 9                         operation,
     10 		],
     11 	},

/usr/local/lib/python2.7/dist-packages/stellar_base-0.0.1-py2.7.egg/stellar_base/transaction.pyc in __init__(self, source, opts)
     22         assert decode_check('account', source)
     23         assert type(opts) is dict
---> 24         assert opts.get('sequence') is not None
     25 
     26         self.source = source

AssertionError:

**Comment by jobforp** [comment]
resoved it with the two patches I submitted

**Comment by Akuukis** [comment]
Thanks! #36, #37

Amount is string to evade Javascript floating point rounding errors, see #34
