### ISSUE TITLE
How can I access the Horizon:Error Response after raising error in code

### ISSUE THREAD

**Issue by farzbood** [StellarCN/py-stellar-base#350]
After an error raised during a Transaction submission with **server.submit_transaction()** how can I access the corresponding **(Horizon Response JSON object)** https://developers.stellar.org/api/errors/response/ in my App's code in order to investigate the **"`result_codes`"** entry and handle the cause of the error(e.g: tx_insufficient_fee), programatically without halting the execution of my code forcefully (which is what happens now).

Stay Safe

**Comment by overcat** [comment]
Hi, hope this demo helps.

```python
from stellar_sdk import Server
from stellar_sdk.exceptions import BaseHorizonError

server = Server("https://horizon.stellar.org")

invalid_xdr = "AAAAANPRjCD1iCti3hovsrrz6aSAjmp263grVr6+mI3SQSkcAAAAZAAPRLgAAAADAAAAAAAAAAAAAAABAAAAAQAAAACuSL9OciKkFztj4d3zuadl20HHObu+7qJenBxHPrMayQAAAAUAAAABAAAAANPRjCD1iCti3hovsrrz6aSAjmp263grVr6+mI3SQSkcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtJBKRwAAABA1N0iqDAgqS6+3RIZGoNB9OXrY3wd/nLruXYi+eiTt4jn94fLVLwAw6jJCaK+qxStwO7c4kP6u5k0RPbuYC55CT6zGskAAABAiUGCNCS4pGlfcRmi82kbralzcFlTQAFzLyfUrYGn3RtQ4p/7TUwAqIanVoWGfEqzIJo64ZT+mYtJ72BfI+FiDg=="
try:
    server.submit_transaction(invalid_xdr, skip_memo_required_check=True)
except BaseHorizonError as err:
    print(err.extras.get("result_codes"))
```

**Comment by farzbood** [comment]
Absolutely.
I've caught sub-classes (exceptions.BadRequestError, exceptions.BadResponseError, etc.) so far, which seems doesn't contain these atrributes, right?
Thanks a lot
Stay Safe V
