### ISSUE TITLE
How to get "offer_id" after successful submission of a ManageBuy/SellOffer Operation

### ISSUE THREAD

**Issue by farzbood** [StellarCN/py-stellar-base#351]
Hi,
I was trying to get the "`offer_id`" of my **sell/buy offers** after their creation, in order to keep them in my local db.
Just found this answer https://stellar.stackexchange.com/questions/2357/python-retrieve-offer-id-from-a-manage-offer-operation
but that code raises this exception in execution, **(Exception has occurred: AttributeError
'nullclass' object has no attribute 'manageOfferResult')** about "`tr.manageOfferResult`" the Transction is successful and all those attributes are available in the Watch-Window of Debug_Pane of VS-Code.
Any solution?

**Comment by overcat** [comment]
Because the Stellar Protocol has been upgraded, the previous answers are no longer available.
Also See: https://github.com/stellar/go/issues/299

```python
import base64

from stellar_sdk.xdr import Xdr

# For ManageBuyOffer
manage_buy_offer_result_bytes = base64.b64decode("AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAMNDf2Rf64eKhSGaRyAFI+niTmzvSeAlM9Mxn8Pv+FxXAAAAAAE3rRkAAAACSGVsbG8AAAAAAAAAAAAAAFodSwcDuUvErN6PJ+Au1DAE6D07eC1e5SKynQKImzUyAAAAAAAAAAAF9eEAAAAAAQAAAAEAAAAAAAAAAAAAAAA=")
tx_result = Xdr.StellarXDRUnpacker(manage_buy_offer_result_bytes).unpack_TransactionResult()
offer_id = tx_result.result.results[0].tr.manageBuyOfferResult.success.offer.offer.offerID
print(offer_id)

# For ManageSellOffer
manage_sell_offer_result_bytes = base64.b64decode('AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAMNDf2Rf64eKhSGaRyAFI+niTmzvSeAlM9Mxn8Pv+FxXAAAAAAE3uXwAAAACSGVsbG8AAAAAAAAAAAAAAFodSwcDuUvErN6PJ+Au1DAE6D07eC1e5SKynQKImzUyAAAAAAAAAAA7msoAAAAAAgAAAAEAAAAAAAAAAAAAAAA=')
tx_result = Xdr.StellarXDRUnpacker(manage_sell_offer_result_bytes).unpack_TransactionResult()
offer_id = tx_result.result.results[0].tr.manageSellOfferResult.success.offer.offer.offerID
print(offer_id)
```

**Comment by farzbood** [comment]
Greate!
Thanks for guidance.
BTW:
While I was digging the SDK code, it comes to my attention that in https://github.com/StellarCN/py-stellar-base/blob/master/stellar_sdk/operation/utils.py "`check_price()`" method, seems the error-message part referring to "`amount`" better off be the "`price`" for sake of **avoiding confusion** between "`amount`" and "`price`" for the target.

Stay Safe V

**Comment by overcat** [comment]
> Hi,
> 
> `from stellar_sdk.xdr import Xdr` no longer works with sdk version 5.0.0
> 
> What is the correct way to retrieve the `offer_id` now?

This changed in [3.0.0](https://github.com/StellarCN/py-stellar-base/blob/master/CHANGELOG.md#version-300).

```python
from stellar_sdk.xdr import TransactionResult

# For ManageBuyOffer
xdr = "AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAMNDf2Rf64eKhSGaRyAFI+niTmzvSeAlM9Mxn8Pv+FxXAAAAAAE3rRkAAAACSGVsbG8AAAAAAAAAAAAAAFodSwcDuUvErN6PJ+Au1DAE6D07eC1e5SKynQKImzUyAAAAAAAAAAAF9eEAAAAAAQAAAAEAAAAAAAAAAAAAAAA="
tr = TransactionResult.from_xdr(xdr)
print(
    tr.result.results[0].tr.manage_buy_offer_result.success.offer.offer.offer_id.int64
)

# For ManageSellOffer
xdr = "AAAAAAAAAGQAAAAAAAAAAQAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAMNDf2Rf64eKhSGaRyAFI+niTmzvSeAlM9Mxn8Pv+FxXAAAAAAE3uXwAAAACSGVsbG8AAAAAAAAAAAAAAFodSwcDuUvErN6PJ+Au1DAE6D07eC1e5SKynQKImzUyAAAAAAAAAAA7msoAAAAAAgAAAAEAAAAAAAAAAAAAAAA="
tr = TransactionResult.from_xdr(xdr)
print(
    tr.result.results[0].tr.manage_sell_offer_result.success.offer.offer.offer_id.int64
)
```

**Comment by Dragon2fly** [comment]
Thank you, it worked.

This should be on the docs.
It would be better if we have an option when calling ManageBuy/SellOffer op to include this `offer_id ` when it returns the response.

**Comment by overcat** [comment]
> Thank you, it worked.
> 
> This should be on the docs. It would be better if we have an option when calling ManageBuy/SellOffer op to include this `offer_id ` when it returns the response.

Thanks, I will add it to the document.
