### ISSUE TITLE
SEP-10 Manage Data Op Changes

### ISSUE THREAD

**Issue by JakeUrban** [StellarCN/py-stellar-base#364]
The following [changes](https://github.com/stellar/stellar-protocol/commit/28c636b4ef5074ca0c3d46bbe9bf0f3f38095233#diff-72480d0894ae2d1a31c229b64ad4c37b) were recently merged to [SEP-10](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md):

- [] the Manage Data operation's key includes a `homeDomain` [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name) instead of the `anchorName` string
- [] a `SIGNING_KEY` attribute in the [stellar.toml](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md) of the service implementing SEP-10 is required
- [] client applications _must_ match the value of the Manage Data operation's key with the home domain used in the request for the service's TOML file
- [] client applications _must_ verify that the service's `SIGNING_KEY` keypair was used to sign the challenge transaction

Each SDK must update to enable the _first_ and ideally _third_ item in this list.

The SDF's JavaScript SDK released [v5.0.5](https://github.com/stellar/js-stellar-sdk/releases/tag/v5.0.5) recently including these changes.

The Go SDK may not support verifying the home domain from the Manage Data op key because it would require breaking changes to `ReadChallengeTx()` and other functions, compared to the strictly additive changes made to the JS SDK. If your SDK would also require breaking changes to implement this check, comment on this issue and we discuss the viability of different options.

If your SDK has implemented and released these changes, reference the release in a closing comment.

**Comment by overcat** [comment]
I already posted a release yesterday, please see the release log for details.
https://github.com/StellarCN/py-stellar-base/releases/tag/2.7.0
