### ISSUE TITLE
get XLM balance of an account

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [StellarCN/py-stellar-base#376]
Hi. how can I get the XLM balance of an account on testnet network? I couldn't find any example or an explicit explanation in the documentation.

**Comment by overcat** [comment]
An example:
```python
from stellar_sdk import Server

account_id = "GD2J5ZZTU4XM5LEX3XPKSCJIQ3UMXU7NLZMHOZEMELXKI4XLPHHKGVM5"

server = Server("https://horizon-testnet.stellar.org")
resp = server.accounts().account_id(account_id).call()

for balance in resp['balances']:
    if (balance['asset_type'] == 'native'):
        print(f'XLM: {balance["balance"]}')
```

**Comment by mgrazianoc** [comment]
`server.accounts()` could be a bit better documented.

Glad I've found this, since in **js** `server.loadDccount()` did the job.

**Comment by overcat** [comment]
> `server.accounts()` could be a bit better documented.
> 
> Glad I've found this, since in **js** `server.loadDccount()` did the job.

Sorry, I missed this reply, will update the document later.
