### ISSUE TITLE
Ensure that it's possible to create accounts with zero starting balance.

### ISSUE THREAD

**Issue by Shaptic** [StellarCN/py-stellar-base#387]
With the introduction of Protocol 14 and specifically [CAP-33](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0033.md), accounts can now be created **without** a starting balance when they are sponsored.

The [CAP notes](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0033.md#operation-validity-changes):
> **Operation Validity Changes**  
> Any downstream system relying on the fact that `CreateAccountOp` is invalid if `startingBalance = 0` will be affected.

This subtlety is easy to overlook, so please ensure that the SDK allows this updated constraint.

**If this SDK validates the starting balance to prevent starting balances of zero, please update the SDK to allow it.** When a transaction is submitted the Stellar network will ensure the amount is non-zero if it needs to be in the specific situations it is required, but SDKs should no longer require it for all cases.

**Comment by overcat** [comment]
Hi, we did not impose restrictions on it, so no modification is required.
