### ISSUE TITLE
stellar-sdk depends on PyNaCl 1.3.0, which has known build time issue on aarch64

### ISSUE THREAD

**Issue by niklasb** [StellarCN/py-stellar-base#412]
**Describe the bug**

stellar-sdk forces PyNaCl version 1.3.0, which has a known issue on aarch64: https://github.com/jedisct1/libsodium/issues/890 

This issue is fixed in PyNaCl 1.4.0.

**What version of dependencies are you using?**

**To Reproduce**

1. Try to install stellar-sdk package on aarch64 (e.g. within a Docker container on a M1 MacBook)
2. Observe build failure when trying to build PyNaCl 1.3.0 dependency

**Expected behavior**

stellar-sdk should support PyNaCl 1.4.0

**Additional context**

**Comment by overcat** [comment]
Thank you for your feedback, I submitted a [new release](https://github.com/StellarCN/py-stellar-base/releases/tag/2.10.1-beta0). You can run it with the following command,

```
pip install stellar-sdk==2.10.1b0
```


If everything works well, please let me know so that I will release an official version. 😃

**Comment by niklasb** [comment]
thank you @overcat, I cannot verify that the library works properly with the new PyNaCl version (I assume there are test suites for this), but I can confirm that the dependency issue is solved and it can be compiled and installed correctly on an M1 macbook now

**Comment by overcat** [comment]
Thanks, closed via https://github.com/StellarCN/py-stellar-base/releases/tag/2.10.1
