### ISSUE TITLE
How to sign from a different place for a multisig transaction

### ISSUE THREAD

**Issue by adeebabdulsalam** [StellarCN/py-stellar-base#415]
All the examples about multi signature transactions shows signing a transaction from the same line of script. This doesn't make sense in practical case. If the second signer seed is in different location how do I send the transaction envelope(XDR) after signing to my partner account which will sign it with his secret seed and then submit ?

The problem I face is after signing the object becomes unusable as it return None

It should be something like
my_tx = TransactionEnvelope(tx,passphrase).sign(acc1_seed)
send(my_tx.to_xdr())

//////receiving end
recv(tx_signed)
tx = TransactionEnvelope.from_xdr(tx_signed,passphrase)
tx.sign(acc2_seed)
server.submit_transaction(tx)

**Comment by overcat** [comment]
Hi, I've added an example, hope this helps.

https://github.com/StellarCN/py-stellar-base/blob/dev/examples/multisig_xdr.py

**Comment by overcat** [comment]
`TransactionEnvelope(tx,passphrase).sign(acc1_seed)` returns None because `sign` is changing the state of the original instance, so it does not return a new instance.

**Comment by adeebabdulsalam** [comment]
> Hi, I've added an example, hope this helps.
> 
> https://github.com/StellarCN/py-stellar-base/blob/dev/examples/multisig_xdr.py
Thanks, It helped
