### ISSUE TITLE
Discussion: Make Transaction source type consistent with Operations?

### ISSUE THREAD

**Issue by JakeUrban** [StellarCN/py-stellar-base#433]
**Is your feature request related to a problem? Please describe.**

Polaris currently populates the SEP-24  `GET /transaction(s)` `from` field using  `Operation.source` or `Transaction.source` [source](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/management/commands/watch_transactions.py#L193-L213)

It was recently reported that `Transaction.source` is a Keypair object, whereas `Operation.source` is a string of the public key. This means Polaris currently returns a `Keypair` object string representation in the `from` field when the `Operation.source` is not populated:

<img width="381" alt="Screen Shot 2021-02-16 at 9 54 04 AM" src="https://user-images.githubusercontent.com/10968980/108108889-15299380-7046-11eb-9c25-48c44bc44ec0.png">

**Describe the solution you'd like**

Ideally, `Operation.source` and `Transaction.source` would be the same data type to avoid bugs like the one reported. However I recognize that would be a breaking change.

**Describe alternatives you've considered**

Keeping it as-is

**Comment by overcat** [comment]
Hi @JakeUrban, I agree with your point about making them type consistent, I think returning `Keypair` is a good choice. It's a change that has wider implications, do you mind if I postpone this change to v4.0?

**Comment by overcat** [comment]
In v4.x, the types of `Operation.source` and `Transaction.source` are both MuxedAccount.
