### ISSUE TITLE
How can i setup stellar sdk with venv ?

### ISSUE THREAD

**Issue by ObiajuluM** [StellarCN/py-stellar-base#435]
I'm running ubuntu on virtual box in windows, python 3.6.
The steps i followed are listed below:
1. i created a virtual environment using `python3 -m venv venv`.
2. i activated the environment.
3. i ran `pip3 install stellar-sdk==3.1.1`.
All installations go well except crc16 and 2 other packages, but if i replicate the same procedure without a virtual environment there are no errors and yes i had the same error on windows that is why i decided to use ubuntu.
NB: i also tried to install the sourcecode locally and build but i had the same issues.

**Comment by overcat** [comment]
Hi @ObiajuluM, would you mind providing the error log?

**Comment by overcat** [comment]
Hi @ObiajuluM, you can try to install `gcc` and `python3-dev` first 

```sh
sudo apt-get install gcc python3-dev
```

**Comment by overcat** [comment]
Since there has been no response for a long time, I am closing this issue now. If you are still confused by this issue, please reopen it. Thanks.
