### ISSUE TITLE
Readme.md examples are incorrect for checking blanace

### ISSUE THREAD

**Issue by bscain** [StellarCN/py-stellar-base#44]
Readme.md is incorrect per the implementation of the address.py.

"now you can check address.balance ,sequence ,flags ,signers, manage_data etc."
should be:
"now you can check address.balances ,sequence ,flags ,signers, manage_data etc."

(Added an "s" to balance for proper variable naming)

**Comment by tangshuran** [comment]
Thanks, already fixed.

**Comment by manran** [comment]
Thanks @bscain  @tangshuran
