### ISSUE TITLE
AiohttpClient requests raise built-in ConnectionError

### ISSUE THREAD

**Issue by JakeUrban** [StellarCN/py-stellar-base#440]
**Describe the bug**
The `AiohttpClient` class raises the builtin python `ConnectionError` exception instead of `stellar_sdk.exceptions.ConnectionError`. The docstring suggests the SDK exception is raised.

**What version of dependencies are you using?**
SDK v2.11

**To Reproduce**
N/A

**Expected behavior**
`AiohttpClient` should raise `stellar_sdk.exceptions.ConnectionError` to be consistent with other SDK clients

**Comment by overcat** [comment]
I'm sorry about this, will fix it as soon as possible.

**Comment by overcat** [comment]
Hi @JakeUrban, did you encounter this error when submiting the transaction?

**Comment by overcat** [comment]
fixed in [2.11.2](https://github.com/StellarCN/py-stellar-base/releases/tag/2.11.2) and [3.1.3](https://github.com/StellarCN/py-stellar-base/releases/tag/3.1.3).

**Comment by JakeUrban** [comment]
Thanks @overcat, and no I was just writing code and making sure I understood the async client behavior.

**Comment by JakeUrban** [comment]
I see you also updated the `except` clause to catch the generic `aiohttp.ClientError` exception, thanks for doing that. Feel free to close!

**Comment by overcat** [comment]
@JakeUrban, thanks for the feedback, I'm actually curious how many people are using the synchronous client and how many are using the asynchronous client. In the future I may refactor the current Server modules and split them into separate Synchronous Server and Asynchronous Server.

**Comment by JakeUrban** [comment]
Polaris uses the synchronous client in most situations, but uses the async client to stream payments to the anchor's distribution accounts concurrently.

I'm considering using it more, but asynchronous code is difficult to test when running Python 3.7, since asynchronous support was not added to common testing libraries until 3.8. I'll likely wait until Polaris 2.0 to upgrade the Python version, and may introduce the additional async support then.

**Comment by overcat** [comment]
Thanks.
