### ISSUE TITLE
Retry() should use 'allowed_methods' in RequestsClient.__init__()

### ISSUE THREAD

**Issue by JakeUrban** [StellarCN/py-stellar-base#444]
**Is your feature request related to a problem? Please describe.**
No problem, just removing a warning message:

![Screen Shot 2021-03-08 at 4 39 26 PM](https://user-images.githubusercontent.com/10968980/110400655-dd9e7d80-802c-11eb-8258-f620d20d2de6.png)

**Describe the solution you'd like**
Change the parameter name from `method_whitelist` to `allowed_methods`

This is low-priority.

**Comment by overcat** [comment]
Resolved and will be included in the next release.
