### ISSUE TITLE
Failed building wheel and setup 

### ISSUE THREAD

**Issue by nikoloskid** [StellarCN/py-stellar-base#447]
### **Environment**
Python version: 3.9.2
Pip version: 21.0.1
Operating System: Windows 20H2

### **Details**
When installing stellar-sdk from pip 

pip install stellar-sdk==3.1.3
Collecting stellar-sdk==3.1.3
  Using cached stellar_sdk-3.1.3-py3-none-any.whl (390 kB)
Requirement already satisfied: mnemonic==0.19 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (0.19)
Requirement already satisfied: aiohttp==3.7.4 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (3.7.4)
Requirement already satisfied: certifi==2020.12.5 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (2020.12.5)
Collecting crc16==0.1.1
  Using cached crc16-0.1.1.zip (20 kB)
Requirement already satisfied: six==1.15.0 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (1.15.0)
Requirement already satisfied: toml==0.10.2 in c:\users\daniel nikoloski\appdata\roaming\python\python39\site-packages (from stellar-sdk==3.1.3) (0.10.2)
Collecting aiohttp-sse-client==0.2.0
  Using cached aiohttp_sse_client-0.2.0-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: pycparser==2.20 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (2.20)
Requirement already satisfied: typing-extensions==3.7.4.3 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (3.7.4.3)
Requirement already satisfied: idna==2.10 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (2.10)
Requirement already satisfied: requests==2.25.1 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (2.25.1)
Requirement already satisfied: cffi==1.14.5 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (1.14.5)
Requirement already satisfied: multidict==5.1.0 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (5.1.0)
Requirement already satisfied: async-timeout==3.0.1 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (3.0.1)
Requirement already satisfied: stellar-base-sseclient==0.0.21 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (0.0.21)
Requirement already satisfied: pynacl==1.4.0 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (1.4.0)
Requirement already satisfied: chardet==3.0.4 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (3.0.4)
Requirement already satisfied: urllib3==1.26.3 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (1.26.3)
Requirement already satisfied: yarl==1.6.3 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (1.6.3)
Requirement already satisfied: attrs==20.3.0 in c:\users\daniel nikoloski\appdata\local\programs\python\python39\lib\site-packages (from stellar-sdk==3.1.3) (20.3.0)
Building wheels for collected packages: crc16
  Building wheel for crc16 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\daniel nikoloski\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Daniel Nikoloski\\AppData\\Local\\Temp\\pip-install-bpi41_vo\\crc16_54c22cded4664e2683b6c1d9f1b062e4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Daniel Nikoloski\\AppData\\Local\\Temp\\pip-install-bpi41_vo\\crc16_54c22cded4664e2683b6c1d9f1b062e4\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Daniel Nikoloski\AppData\Local\Temp\pip-wheel-zw7ufwol'
       cwd: C:\Users\Daniel Nikoloski\AppData\Local\Temp\pip-install-bpi41_vo\crc16_54c22cded4664e2683b6c1d9f1b062e4\
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\crc16
  copying python3x\crc16\crc16pure.py -> build\lib.win-amd64-3.9\crc16
  copying python3x\crc16\test.py -> build\lib.win-amd64-3.9\crc16
  copying python3x\crc16\__init__.py -> build\lib.win-amd64-3.9\crc16
  running build_ext
  building 'crc16._crc16' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for crc16
  Running setup.py clean for crc16
Failed to build crc16
Installing collected packages: crc16, aiohttp-sse-client, stellar-sdk
    Running setup.py install for crc16 ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\daniel nikoloski\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Daniel Nikoloski\\AppData\\Local\\Temp\\pip-install-bpi41_vo\\crc16_54c22cded4664e2683b6c1d9f1b062e4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Daniel Nikoloski\\AppData\\Local\\Temp\\pip-install-bpi41_vo\\crc16_54c22cded4664e2683b6c1d9f1b062e4\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Daniel Nikoloski\AppData\Local\Temp\pip-record-hpryd05z\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\daniel nikoloski\appdata\local\programs\python\python39\Include\crc16'
         cwd: C:\Users\Daniel Nikoloski\AppData\Local\Temp\pip-install-bpi41_vo\crc16_54c22cded4664e2683b6c1d9f1b062e4\
    Complete output (12 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\crc16
    copying python3x\crc16\crc16pure.py -> build\lib.win-amd64-3.9\crc16
    copying python3x\crc16\test.py -> build\lib.win-amd64-3.9\crc16
    copying python3x\crc16\__init__.py -> build\lib.win-amd64-3.9\crc16
    running build_ext
    building 'crc16._crc16' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\daniel nikoloski\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Daniel Nikoloski\\AppData\\Local\\Temp\\pip-install-bpi41_vo\\crc16_54c22cded4664e2683b6c1d9f1b062e4\\setup.py'"'"'; __file__='"'"'C:\\Users\\Daniel Nikoloski\\AppData\\Local\\Temp\\pip-install-bpi41_vo\\crc16_54c22cded4664e2683b6c1d9f1b062e4\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Daniel Nikoloski\AppData\Local\Temp\pip-record-hpryd05z\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\daniel nikoloski\appdata\local\programs\python\python39\Include\crc16' Check the logs for full command output.

**Comment by overcat** [comment]
Hello, can you try to install Microsoft C++ Build Tools first?  This problem can usually be solved after installing it.  

Some reference links:
- https://stackoverflow.com/a/64262038
- https://answers.microsoft.com/en-us/windows/forum/all/microsoft-visual-c-140/6f0726e2-6c32-4719-9fe5-aa68b5ad8e6d

**Comment by nikoloskid** [comment]
> Hello, can you try to install Microsoft C++ Build Tools first? This problem can usually be solved after installing it.
> 
> Some reference links:
> 
> * https://stackoverflow.com/a/64262038
> * https://answers.microsoft.com/en-us/windows/forum/all/microsoft-visual-c-140/6f0726e2-6c32-4719-9fe5-aa68b5ad8e6d

Awesome, that fixed it!

**Comment by overcat** [comment]
You're welcome, I am closing the issue now.
