### ISSUE TITLE
Regression in SEP-0010 checking client signers

### ISSUE THREAD

**Issue by itsmecurtis** [StellarCN/py-stellar-base#463]
I believe the `continue` introduced here in #428 has caused a regression as when there is only a single client signer now and `signer.account_id == client_signing_key` the call to `signers_found.append(signer)` on L336 never happens and so L352-L353 always raise "Transaction not signed by any client signer."

https://github.com/StellarCN/py-stellar-base/blob/c133995cf636c69b0e691c509b7f0650e5626555/stellar_sdk/sep/stellar_web_authentication.py#L330-L353

There doesn't seem to be a test that calls `verify_challenge_transaction_signers` with only a single client signature passed in; they all sign with at least two client signers so one of them ultimately hits L336 and they all pass.

**Comment by overcat** [comment]
Hi @itsmecurtis, I have thought about this scenario before, can you check [this conversation](https://github.com/StellarCN/py-stellar-base/pull/428#discussion_r569098889)?

**Comment by overcat** [comment]
This issue is closed due to not being active. Please feel free to reopen it again if you still encounter this issue with the [latest version](https://pypi.org/project/stellar-sdk/).

Thank you!
