### ISSUE TITLE
"Invalid code" decoding TransactionResultPair with a failed operation

### ISSUE THREAD

**Issue by RichardWarfield** [StellarCN/py-stellar-base#468]
I'm getting a `ValueError` when trying to parse a TransactionResultPair.  Possibly this is expected behavior which I am misunderstanding but I would expect the result object to be decoded with the error code rather than throwing an exception.

Take for example transaction `92b77300c781af6363af584504659cd83d7d00432b31dd1b06b7562584e91ef5` on the public network, for which the base64 txresult is `krdzAMeBr2Njr1hFBGWc2D19AEMrMd0bBrdWJYTpHvUAAAAAAAAnEf////8AAAABAAAAAAAAAAL////2AAAAAA==`.

calling:
```python
 stellar_sdk.xdr.transaction_result_pair.TransactionResultPair.from_xdr(txresult)
```

Results in 
```
ValueError: Invalid code.
> /home/richard/.local/lib/python3.8/site-packages/stellar_sdk/xdr/path_payment_strict_receive_result.py(85)unpack()
     83                 raise ValueError("no_issuer should not be None.")
     84             return cls(code, no_issuer=no_issuer)
---> 85         raise ValueError("Invalid code.")
     86
     87     def to_xdr_bytes(self) -> bytes:
```

Inspecting the value of `code` here I see that it is `PathPaymentStrictReceiveResultCode.PATH_PAYMENT_STRICT_RECEIVE_TOO_FEW_OFFERS`.  

The generated code here seems to be missing some branches.

**Comment by overcat** [comment]
Thanks for your feedback, the v3 version uses the new XDR generator, which caused this bug, and I am already working on fixing it. You can use the v2 version first, thank you.

https://github.com/StellarCN/py-stellar-base/tree/v2

```
pip install stellar-sdk==2.13.0
```

**Comment by overcat** [comment]
Hi @RichardWarfield, apologize for the inconvenience caused, we have fixed this issue in [3.3.1](https://github.com/StellarCN/py-stellar-base/releases/tag/3.3.1).

PyPi Package: https://pypi.org/project/stellar-sdk/3.3.1/

```
pip install stellar-sdk==3.3.1
```

Thanks for your feedback :-)

**Comment by RichardWarfield** [comment]
Thank you!

**Comment by RichardWarfield** [comment]
Can confirm this is working correctly now, so I'll close this.
