### ISSUE TITLE
Transactions call builder

### ISSUE THREAD

**Issue by AnimusXCASH** [StellarCN/py-stellar-base#495]
Hey, 

recently I have started to receive errors on transactions call builder for the account. It seems like the .cursor() is making an issue.

Without cursor works normally and i get response from the horizon server: 
```python
data = server.transactions().for_account(account_id=f"{pub_key}").call()```

 or  

 data = server.transactions().for_account(
        account_id=account_id=f"{pub_key}").include_failed(False).order(
            desc=False).limit(50).call()
```

however this is failing: 

````python
data = server.transactions().for_account(account_id=f"{pub_key}").include_failed(False).order(
        desc=False).cursor(154450799240826880).limit(200).call()
````
        
 Response I am getting is:
 
 ```json
 {
  "type": "https://stellar.org/horizon-errors/service_unavailable",
  "title": "Service Unavailable",
  "status": 503,
  "detail": "The request cannot be serviced at this time."
}
```
        
Any suggestions maybe?

Thank you for your time help and answer/assistance with this issue.

**Comment by overcat** [comment]
Hi, which horizon are you connected to? I connected to https://horizon.stellar.org/ for testing and everything is working fine. You can try to build the request [here](https://laboratory.stellar.org/#explorer?resource=transactions&endpoint=for_account&network=public) and see if you get the same error.

**Comment by AnimusXCASH** [comment]
To same as you have tested.

Its odd that it works normally on my personal computer, my Vbox, even tested it on my home Raspberry ubuntu server and it worked. While on the Hetzner server it does not and same code is deployed. I have not done any modifications to stellar sdk or what so ever.

If i make a call to horizon through use of requests library it works on the server as well.

Is it possible to get the URI out which is created through the package?

Animus

**Comment by overcat** [comment]
@AnimusXCASH Thanks for your feedback. Personally, I would prefer this to be a horizon glitch. If you want to get a link to the request, you can do so in the following way.
```python
from stellar_sdk import Server
import os

server = Server("https://horizon.stellar.org/")

builder = server.transactions().for_account(
    account_id="your_account_id").include_failed(False).order(
    desc=False).cursor(154450799240826880).limit(200)
print(f"endpoint: {os.path.join(builder.horizon_url, builder.endpoint)}")
print(f"params: {builder.params}")
data = builder.call()
print(f"data: {data}")
```

**Comment by AnimusXCASH** [comment]
Thats what i get out
```endpoint: https://horizon.stellar.org/accounts/GA7W3SFEZ6BSBW3JDUA5622X7EDJF2PZQQTWZVDKF4HF47CRVH6UCDAV/transactions
params: {'include_failed': 'false', 'order': 'asc', 'cursor': '154450799240826880', 'limit': '200'}
```

**Comment by AnimusXCASH** [comment]
@overcat I have been investing a bit on the server instance and came to conclusion that there is certain paging height where it fails for me:

````
Cursor paging height: 155402125906796544 WORKS
Cursor paging height: 154925745315446784 FAILS
Cursor paging height: 154471410788945920 WORKS
````
With the help from  **earrietadev**  from the Discord server on Stellar Global he informed me that its the Horizon Stellar instance issue as:

Quote from him

````

https://horizon.stellar.lobstr.co/accounts/GA7W3SFEZ6BSBW3JDUA5622X7EDJF2PZQQTWZVDKF4HF47CRVH6UCDAV/transactions?cursor=154925745315446784 pass

https://horizon.stellar.org/accounts/GA7W3SFEZ6BSBW3JDUA5622X7EDJF2PZQQTWZVDKF4HF47CRVH6UCDAV/transactions?cursor=154925745315446784 fails

```

Thanks for help

**Comment by overcat** [comment]
@AnimusXCASH Thanks, you can raise an issue [here](https://github.com/stellar/go/issues) if you want to know why there is such a difference.
