### ISSUE TITLE
On checking the signer of an envelope

### ISSUE THREAD

**Issue by Fanbingxia** [StellarCN/py-stellar-base#51]
Hi, I want to check the signatures on an envelope (basically I hope to get something like an address). I run the code:
envelope.signatures
and it returned me something like:
[DecoratedSignature(hint=b'\xb1.{;', signature=b'\x1b\x03#\xf2\xb2\xa9\xee\xa1n\xa5\xb7\xbd\xa5\x94\x9f\xdcq\xa5\xc5`\xfc-\xf8\xc5\xc7\x84\xd5\x81\x03\x0e\x0c&\xcb\xe8\x85\xfa\xff\xc4\x1f\xbc\xcc\xefr\xd8\xa3\xff\xd9\x8bg\xdb^C]u\xe1\x1ch\xcf\xad\x8a\x9c\xbe\x95\x0c')]
I want to ask how do I decrypt this DecoratedSignature into something that is actually recognisable?
Thank you very much.

**Comment by overcat** [comment]
No, You can only get information from the XDR(https://www.stellar.org/laboratory/#xdr-viewer)
