### ISSUE TITLE
SEP-10: apply grace period to minTime constraint (SDF)

### ISSUE THREAD

**Issue by JakeUrban** [StellarCN/py-stellar-base#524]
## SEP-10: Apply grace period to `minTime` constraint

It is possible that the client machine's clock is behind the SEP-10 server machine's clock.

If this is the case, client applications calling `readChallengeTx()` may not be able to validate the challenge due to the challenge transaction's minimum timebound being greater than the client machine's current time.

#### `readChallengeTx()` or the equivalent function

- Apply a 5-minute grace period to the minibum timebound check
  - i.e. the minimum timebound should be permitted to be at most 5 minutes in the future from the client machine's current time

### Implementations

Both the JS and Go SDKs have been updated with these changes.

- [stellar/js-stellar-sdk#667](https://github.com/stellar/js-stellar-sdk/pull/667)
  - The JS SDK also applied the grace period to the maximum timebound, but the minimum timebound is the more important constraint to relax.
- [stellar/go#3824](https://github.com/stellar/go/pull/3824)

**Comment by JakeUrban** [comment]
https://github.com/stellar/stellar-protocol/issues/1057

**Comment by overcat** [comment]
Added in v4.2.1.
