### ISSUE TITLE
amm.py from examples not worked

### ISSUE THREAD

**Issue by minherc** [StellarCN/py-stellar-base#553]
**Describe the bug**
Requires asset (LP) issuer.
In the LiquidityPool example, you didn't have it.
/py-stellar-base/example/amm.py

```
/py-stellar-base/examples#` python3 amm1.py
Liquidity Pool ID: 0aeafb6dda1a3ccc1693a81ffbd0271e8e128d77cc46698fdf1d589c2670e2bd
Traceback (most recent call last):
  File "amm1.py", line 42, in <module>
    .append_change_trust_op(liquidity_pool_asset)
TypeError: append_change_trust_op() missing 1 required positional argument: 'asset_issuer'
```

**CODE**

```
from stellar_sdk import (
    Asset,
    Keypair,
    LiquidityPoolAsset,
    LIQUIDITY_POOL_FEE_V18,
    Network,
    Server,
    TransactionBuilder,
)

horizon_url = "https://horizon.stellar.org/"
#network_passphrase = Network.TESTNET_NETWORK_PASSPHRASE
network_passphrase = Network.PUBLIC_NETWORK_PASSPHRASE

server = Server(horizon_url=horizon_url)
source_keypair = Keypair.from_secret(
    "S*************************************************"
)

# We assume that Hello asset already exists in the Stellar network,
# and you can learn how to issue assets through examples/issue_asset.py
# Here we define a Liquidity Pool Asset.
asset_a = Asset.native()
asset_b = Asset("MERA", "G**************************************7H2A")
fee = LIQUIDITY_POOL_FEE_V18 # tried it with and without
liquidity_pool_asset = LiquidityPoolAsset(asset_a=asset_a, asset_b=asset_b, fee=fee)
#print(liquidity_pool_asset)
liquidity_pool_id = liquidity_pool_asset.liquidity_pool_id
print(f"Liquidity Pool ID: {liquidity_pool_id}")

source_account = server.load_account(account_id=source_keypair.public_key)

# First we need to add a trust line for liquidity_pool_asset.
transaction1 = (
    TransactionBuilder(
        source_account=source_account,
        network_passphrase=network_passphrase,
        base_fee=100,
    )
    .append_change_trust_op(liquidity_pool_asset)
    .set_timeout(30)
    .build()
)
transaction1.sign(source_keypair)
response1 = server.submit_transaction(transaction1)
print(response1)
```

I tried a lot of things but didn't work.
One final thought: don't use the append_change_trust_op () wrapper, but use ChangeTrust ().
I don’t think that will help.

**Comment by overcat** [comment]
Sorry for the inconvenience, the example code in the master branch corresponds to version 6.0.0b3, and the version you are currently using may be 5.0.0. Currently you have two options, one is to install version 6.0.0b3, and the other is to view [the example](https://github.com/StellarCN/py-stellar-base/blob/5.0.0/examples/amm.py) corresponding to version 5.0.0.

**Comment by minherc** [comment]
Thanks for the answer, tried it on version 6, doesn't work either. 
The error is the same. 
_TypeError: append_change_trust_op () missing 1 required positional argument: 'asset_issuer'_

```
~/stellar/py-stellar-base-6.0.0-beta3/examples# python3 amm1.py
Liquidity Pool ID: 0aeafb6dda1a3ccc1693a81ffbd0271e8e128d77cc46698fdf1d589c2670e2bd
Traceback (most recent call last):
  File "amm1.py", line 40, in <module>
    .append_change_trust_op(liquidity_pool_asset)
TypeError: append_change_trust_op() missing 1 required positional argument: 'asset_issuer'
```

**Comment by overcat** [comment]
@minherc 

Can you run the following command in the shell and let me know the output?
```
python -c 'import stellar_sdk; print(stellar_sdk.__version__)'
```

**Comment by minherc** [comment]
It turns out that in both installations I have a version of 6 beta.

```
1: stellar/py-stellar-base# python3 setup.py --version
6.0.0b3

2: stellar/py-stellar-base-6.0.0-beta3#  python3 setup.py --version
6.0.0b3
```
Code from version 5 (https://github.com/StellarCN/py-stellar-base/blob/5.0.0/examples/amm.py) works in version 6)
The code from version 6 does (from examples dir) not work in version 6, how does that happen?

**Comment by overcat** [comment]
What `python3 setup.py --version`  shows is not the version you have installed, use `python3 -c 'import stellar_sdk; print(stellar_sdk.__version__)'` instead, please.

**Comment by overcat** [comment]
You can also install 6.0.0b3 via `pip install .`

**Comment by minherc** [comment]
Strange, but this command shows different versions in different folders.
`python3 -c 'import stellar_sdk; print(stellar_sdk.__version__)'`

```
:~/stellar/py-stellar-base# python3 -c 'import stellar_sdk; print(stellar_sdk.__version__)'
6.0.0b3

:~/stellar/py-stellar-base-6.0.0-beta3#  python3 -c 'import stellar_sdk; print(stellar_sdk.__version__)'
6.0.0b3

:~# python3 -c 'import stellar_sdk; print(stellar_sdk.__version__)'
5.0.0
```

In the user's root folder ~ /
shows version 5.0.0 - apparently this is the version installed globally, via PIP.
Versions 6, beta are installed in the folders, but when starting the amm scripts it is not clear which sdk is used.

Thanks for the quick answers, in my opinion I figured out what the problem is)

ps: exactly, gobally worth 5,0,0
```
~# pip freeze | grep stellar-sdk
stellar-sdk==5.0.0
```
pps:  maybe you add version checking to the main description of the project.
For you it may be obvious, for people like me - no ))
There will be fewer stupid questions.

**Comment by overcat** [comment]
Thank you for your feedback, and sorry for the inconvenience, I will improve it later.

**Comment by minherc** [comment]
And thank you very much for your help!

ps: now added these lines to the script:
import stellar_sdk
print (stellar_sdk .__ version__)

As you would expect, it featured version 5.0.0.
