### ISSUE TITLE
504 timeout error

### ISSUE THREAD

**Issue by DreamHackchosenone** [StellarCN/py-stellar-base#568]
submit a signed tx, always get this error, how to resolve it?
{"code": -32000, "message": "Server error", "data": "HorizonError: Invalid horizon reply: [504] {\'type\': \'https://stellar.org/horizon-errors/timeout\', \'title\': \'Timeout\', \'status\': 504, \'detail\': \'Your request timed out before completing.  Please try your request again. If you are submitting a transaction make sure you are sending exactly the same transaction (with the same sequence number)
server info:
Ubuntu 20.04.3
8 CORE, 32 GMem

**Comment by overcat** [comment]
Please check this thread: https://github.com/stellar/go/issues/305#issuecomment-757007408

**Comment by DreamHackchosenone** [comment]
> Please check this thread: [stellar/go#305 (comment)](https://github.com/stellar/go/issues/305#issuecomment-757007408)

I set num_retries=10, max_fee=500, still not working

**Comment by overcat** [comment]
> > Please check this thread: [stellar/go#305 (comment)](https://github.com/stellar/go/issues/305#issuecomment-757007408)
> 
> I set num_retries=10, max_fee=500, still not working

I think you need to increase `base_fee`, see https://dashboard.stellar.org/

**Comment by DreamHackchosenone** [comment]
> > > Please check this thread: [stellar/go#305 (comment)](https://github.com/stellar/go/issues/305#issuecomment-757007408)
> > 
> > 
> > I set num_retries=10, max_fee=500, still not working
> 
> I think you need to increase `base_fee`, see https://dashboard.stellar.org/

Thanks, my stellar-base version is 1.1.2.0, it seems that this version cant set base_fee, i will upgrade it and try

**Comment by overcat** [comment]
Hope this example is helpful to your migration work. 

https://github.com/StellarCN/py-stellar-base/blob/v6/examples/payment.py

**Comment by DreamHackchosenone** [comment]
> Hope this example is helpful to your migration work.
> 
> https://github.com/StellarCN/py-stellar-base/blob/v6/examples/payment.py

It works! thank you!
