### ISSUE TITLE
stellar-base in pypi is not updated since Apr 20, 2019

### ISSUE THREAD

**Issue by Rutrus** [StellarCN/py-stellar-base#569]
**Describe the bug**
I used to install [stellar-base from pypi](https://pypi.org/project/stellar-base/) I was not aware of the updates or warnings from newer major versions because this repo is not updated there.

**What version of dependencies are you using?**
stellar-base 1.1.2.0

**To Reproduce**
`pip3 install --upgrade stellar-base` is not aware of newer versions.

**Expected behavior**
Install stellar-base 6.1.1

**Additional context**
If there is a new package in pypi or a reason, I would like to know about it.

**Comment by overcat** [comment]
Please uninstall stellar-base and install stellar-sdk instead.

https://pypi.python.org/pypi/stellar-sdk

**Comment by overcat** [comment]
As some of the APIs have changed, I recommend you check the readme file first.

**Comment by Rutrus** [comment]
The description sounds like you are maintaining both. Will you test stellar 1.1.2.0 against python 3.8, 3.9, 3.10...?
Should we deprecate it and install `stellar-sdk` ?

**Comment by overcat** [comment]
For some reason, I don't have the write permission of the stellar-base package on pypi, so I created a new stellar-sdk package instead. They are actually based on the "same" source code. 

You should no longer use stellar-base now, please migrate to stellar-sdk, it has tested on python 3.6~3.10

**Comment by Rutrus** [comment]
Clear. Thank you.
