### ISSUE TITLE
Did the mnemonic capability go away?

### ISSUE THREAD

**Issue by kfiresmith** [StellarCN/py-stellar-base#57]
```python
>>> help(stellar_base.utils.StellarMnemonic)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'stellar_base.utils' has no attribute 'StellarMnemonic'
>>> from stellar_base.utils import StellarMnemonic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'StellarMnemonic'
```

I'm attempting to follow the README.md guidance for creating a deterministic keypair and it's not working out so far. :(

Version information follows:
```
Name: stellar-base
Version: 0.1.5
Summary: Code for managing Stellar.org blockchain transactions and accounts 
    using stellar-base in python. Allows full functionality interfacing
    with the Horizon front end.
Home-page: http://github.com/stellarCN/py-stellar-base/
Author: antb123
Author-email: awbarker@gmail.com
License: Apache
Location: /home/webusr/.local/lib/python3.6/site-packages
Requires: ed25519, crc16, requests, SSEClient, numpy
```

**Comment by kfiresmith** [comment]
So I think I found the problem - the version being supplied in Pypi, 0.1.5, is somehow not as recent or more recent than the master branch that the README is referring to (which I thought was 0.1.0), thus the StellarMnemonic class doesn't exist.  

I'll email the maintainer of the Pypi package to see about getting it updated if I can't find him here on the project :/

**Comment by Gitzman** [comment]
Verifying I have attempted this from the PyPi package from both python 3.6 and 2.7 and it has failed for both.

**Comment by kfiresmith** [comment]
Hi @Gitzman.  I emailed the pypi module author last night to ask for it to be rebased to master.  No word back yet, and couldn't find him on Github

**Comment by kfiresmith** [comment]
Just a note back that I still have not heard from the Pypi module maintainer.  I am wondering if we don't hear from the maintainer for some amount of time if someone else is able to update the module on Pypi?
