### ISSUE TITLE
Executing the streaming example consistently return errors for all endpoint

### ISSUE THREAD

**Issue by Krixzus** [StellarCN/py-stellar-base#573]
Code run:
`USDC_asset = Asset("USDC", "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5")`
`server = Server("https://horizon-testnet.stellar.org")`
`for response in server.orderbook(Asset.native(), USDC_asset).cursor("now").stream():`
`        print(response)`
        

The error message I get:

Traceback (most recent call last):
  File "C:/Users/nasse/Syncthing/Code/Python/Stellar_test/main_order_book.py", line 22, in <module>
    for response in server.orderbook(Asset.native(), USDC_asset).cursor("now").stream():
  File "C:\Users\nasse\Syncthing\Code\Python\Stellar_test\venv_xeon\lib\site-packages\typeguard\__init__.py", line 897, in __next__
    return self.send(None)
  File "C:\Users\nasse\Syncthing\Code\Python\Stellar_test\venv_xeon\lib\site-packages\typeguard\__init__.py", line 915, in send
    value = self.__wrapped.send(obj)
  File "C:\Users\nasse\Syncthing\Code\Python\Stellar_test\venv_xeon\lib\site-packages\stellar_sdk\client\requests_client.py", line 174, in stream
    params=query_params,
  File "C:\Users\nasse\Syncthing\Code\Python\Stellar_test\venv_xeon\lib\site-packages\stellar_sdk\client\requests_client.py", line 222, in __init__
    url, last_id, retry, session, chunk_size, connect_retry, **kwargs
TypeError: __init__() got an unexpected keyword argument 'params'

Process finished with exit code 1

Thank you for your help.

**Comment by overcat** [comment]
Hello, please try to upgrade `stellar-sdk` to the latest version. If this does not solve the problem, please execute `pip freeze` in the console and paste the output here.

You can install the latest version with the following command
```
pip install stellar-sdk==6.1.1
```

**Comment by Krixzus** [comment]
I am the latest version (6.1.1) on Python 3.7. pip freeze returns:

aiohttp==3.8.1
aiohttp-sse-client==0.2.1
aiosignal==1.2.0
async-timeout==4.0.2
asynctest==0.13.0
atomicwrites==1.4.0
attrs==21.3.0
backcall==0.2.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.9
click==8.0.3
colorama==0.4.4
coloredlogs==15.0.1
coverage==6.2
crc16==0.1.1
decorator==5.1.0
ed25519==1.5
fancycompleter==0.9.1
flake8==4.0.1
frozenlist==1.2.0
humanfriendly==10.0
idna==3.3
importlib-metadata==4.2.0
iniconfig==1.1.1
ipython==7.30.1
jedi==0.18.1
marshmallow==3.14.1
matplotlib-inline==0.1.3
mccabe==0.6.1
mnemonic==0.20
multidict==5.2.0
numpy==1.21.5
packaging==21.3
parso==0.8.3
pbkdf2==1.3
pdbpp==0.10.3
pickleshare==0.7.5
pluggy==1.0.0
prompt-toolkit==3.0.24
py==1.11.0
pycodestyle==2.8.0
pycparser==2.21
pyflakes==2.4.0
Pygments==2.11.1
PyNaCl==1.4.0
pyparsing==3.0.6
pyreadline==2.1
pyrepl==0.9.0
PySocks==1.7.1
pytest==6.2.5
pytest-cov==3.0.0
pytest-flake8==1.0.7
pytest-variables==1.9.0
python-dateutil==2.8.2
PyYAML==6.0
requests==2.27.0
requests-mock==1.9.3
six==1.16.0
sseclient==0.0.27
sseclient-py==1.7.2
stellar-base-sseclient==0.0.21
stellar-sdk==6.1.1
toml==0.10.2
tomli==2.0.0
traitlets==5.1.1
typeguard==2.13.3
typing_extensions==4.0.1
urllib3==1.26.7
wcwidth==0.2.5
wmctrl==0.4
yarl==1.7.2
zipp==3.7.0

**Comment by overcat** [comment]
I think it is caused by a dependency conflict, I am checking this issue, will take some time.

**Comment by overcat** [comment]
Hello, are you using a [virtual environment](https://docs.python.org/3/tutorial/venv.html)? If not, I suggest you use it.

I think the conflict is caused by `sseclient` and `sseclient-py`, why are they introduced? If they are not necessary, I think removing them from the dependent files and rebuilding the virtual environment should solve this problem.

**Comment by Krixzus** [comment]
I am using a virtual environment.  I added requests and sseclient-py because the SDK did not work.  The intent was to use the horizon API directly to get the streaming going.  I had some success but the streaming starts with "hello", sends 2 or 3 times the order book and closes with message "byebye".

I will erase my venv folder, only install the stellar-sdk 6.1.1 and see if it is better.

**Comment by Krixzus** [comment]
Wow, it now works very well.  It streams the orderbook in a endless loop, like expected.  Thank you for your help.
