### ISSUE TITLE
helper function to resolve the predicate of a claimable balance 

### ISSUE THREAD

**Issue by hentr** [StellarCN/py-stellar-base#578]
**Is your feature request related to a problem? Please describe.**
These days there are a large number of claimable balances being sent to any active stellar wallet. Since there is a variety of different nested ways to write the predicate logic for these claimable balances, it is non-trivial to robustly determine whether a claimable balance can be claimed or not at present time.

**Describe the solution you'd like**
A helper function is needed to easily resolve the predicate, to determine whether a claimable balance is currently claimable, expired, or will be claimable in the future.

**Additional context**
An example for this kind of helper function exists for javascript: https://github.com/hanseartic/stellar-resolve-claimant-predicates 
This module takes in the predicate and returns: 
{
    status: 'claimable' | 'expired' | 'upcoming';
    predicate: xdr.ClaimPredicate,
    validFrom?: number,
    validTo?: number,
}
which can easily be used to resolve claimable balances.

**Comment by overcat** [comment]
Hello, I will consider adding it. Currently you can refer to this script, it contains a function to help you determine whether the claimant can be claimed: https://gist.github.com/overcat/ac403259747f3428db0121b9a962901d#file-trezor_claim_stellar_balances-py-L96
