### ISSUE TITLE
Send transaction to horizon: "op_too_many_subentries"

### ISSUE THREAD

**Issue by minherc** [StellarCN/py-stellar-base#579]
Sending a large number of operations (1000 = 10 transactions * 100 operations) 
to the network through my horizon, response 400: "op_too_many_subentries"

fee increased to 20000, does not help.

on the stellar-core configuration (stellar-core.cfg), changed the parameters:

FLOOD_OP_RATE_PER_LEDGER=10000
FLOOD_TX_PERIOD_MS=1
didn't help either.

result code:
```"result_codes": {
      "transaction": "tx_failed",
      "operations": [
        "op_success",
        "op_too_many_subentries",
        "op_too_many_subentries",
        "op_too_many_subentries",
        "op_too_many_subentries",
        "op_too_many_subentries",
         ..........................
```
I made delays in the code, it also did not help.
python code:
```
coms =1200
sell_offer_transaction = TransactionBuilder(
                                source_account=source_account,
                                network_passphrase=network_passphrase,
                                base_fee=coms
                            )
        
    for a,b in enumerate(r_aqua_b):
        if a>0 and a % 100 == 0:
#            sell_offer_transaction = sell_offer_transaction.set_timeout(30)
            sell_offer_transaction = sell_offer_transaction.build()
            sell_offer_transaction.sign(seller_secret_key)
            connected = False
            while not connected:
                try:
                    time.sleep(7)
                    sell_offer_transaction_resp = server.submit_transaction(sell_offer_transaction)
                    connected = True
                except Exception as e:
                    coms += 100
                    print(str(e), 'coms:',coms)
            print("sell count: ",a,"\n sum: ",str(round(r1_aqua_b[a],7)), str(1/b), sell_offer_transaction_resp)
#            pprint(vars(sell_offer_transaction.transaction.operations[0]))
            del sell_offer_transaction, sell_offer
            sell_offer_transaction = TransactionBuilder(
                                        source_account=source_account,
                                        network_passphrase=network_passphrase,
                                        base_fee=coms
                                    )
#            time.sleep(15)
        sell_offer = ManageSellOffer(
            selling=asset_a, buying=asset_b, amount=str(round(r1_aqua_b[a],7)), price=str(1/b)
            )
        sell_offer_transaction.append_operation(sell_offer)
#        print(sell_offer)

#    sell_offer_transaction = sell_offer_transaction.set_timeout(30)    
    sell_offer_transaction = sell_offer_transaction.build()
    sell_offer_transaction.sign(seller_secret_key)
    sell_offer_transaction_resp = server.submit_transaction(sell_offer_transaction)
#    print("send last: \n",sell_offer_transaction_resp)

**Comment by hbirkdale** [comment]
@minherc I think you might have hit a limit that we hit a few months back. An account cannot have more than 1000 subentries.  See https://developers.stellar.org/api/errors/result-codes/operation-specific/ and look for:
op_too_many_subentriesopTOO_MANY_SUBENTRIES
Max number of subentries (1000) already reached

**Comment by minherc** [comment]
Thanks for the quick response.
I am talking about ManageSellOffer, and 100 sell operations in each transaction. (this can be seen in the code above)
I have sales operations, not operations with the account and its sub-accounts.
I think we are talking about different things.

**Comment by overcat** [comment]
Hi @minherc, each unfilled offer will also be counted as a subentry_count.

**Comment by minherc** [comment]
@overcat, @hbirkdale, thanks for answers, 
in the account from which transactions are set, subentry_count=997, what does this mean?
Can I send 997 operations in 10 transaction (100 op. jn 1 trans.) at one time from this account?
Where can I read about it, 
what does this indicator mean, 
what does it affect and how can it be managed?

ps the previous 1000 operations from this account have passed.
pps I thought that this was a limitation in my horizon or in stellar-core

**Comment by overcat** [comment]
Hi, hope this article is useful
https://developers.stellar.org/docs/glossary/accounts/#number-of-subentries

**Comment by hbirkdale** [comment]
@minherc My understanding is that the number of operations/transactions you send is technically independent from the number of subentries associated with the account. I could have an account with 10 subentries and the operations and transactions I send will be limited by whatever the operation/transaction limit is. However, if my subentry count is 1000, and I try and send an operation/transaction that adds to the subentries -- that transaction will fail with the too many subentries error.

**Comment by minherc** [comment]
thank you very much, now it is clear that an
 
**STELLAR account cannot have more than 1000 buy/sell offers. (practically less) ))**

does this restriction apply to muxed account?
or each muxed account can have 1000 offers?

**Comment by overcat** [comment]
I think what we are talking about is not related to muxed accounts, even if you use a different muxed account(the 'M...'), as long as the base account(the 'G...') is consistent, then it is still restricted.

**Comment by minherc** [comment]
@overcat , @hbirkdale  
Thank you very much for the explanation,
 there is very little information on this topic.

If someone is looking for ways to fill their trading pairs with offers on stellar dex, they should look for other ways ))

**Comment by overcat** [comment]
Yes, currently if a user wants to create more than 1000 offers, he/she must prepare multiple accounts.

**Comment by hbirkdale** [comment]
> 

That's right. We have an app that digitizes loans into portfolios and that's what we had to do.

**Comment by minherc** [comment]
@hbirkdale, "_digitizes loans into portfolios_" what is it, where can i read about it?
