### ISSUE TITLE
Wordlist not included for StellarMnemonic?

### ISSUE THREAD

**Issue by kfiresmith** [StellarCN/py-stellar-base#58]
I'm running through the documentation on the README.md file for creating a mnemonic keypair seed, and discovered that a mnemonic wordlist doesn't appear to be included, resulting in an ugly traceback for the user.  Please see below:

```python
Python 3.6.3 (default, Oct  9 2017, 12:07:10) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stellar_base.utils import StellarMnemonic
>>> sm = StellarMnemonic()
>>> m = sm.generate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/stellar_base/utils.py", line 236, in generate
    ret = self.to_mnemonic(os.urandom(strength // 8))
  File "/usr/local/lib/python3.6/site-packages/mnemonic/mnemonic.py", line 146, in to_mnemonic
    if self.detect_language(' '.join(result)) == 'japanese':  # Japanese must be joined by ideographic space.
  File "/usr/local/lib/python3.6/site-packages/mnemonic/mnemonic.py", line 78, in detect_language
    languages = cls.list_languages()
  File "/usr/local/lib/python3.6/site-packages/stellar_base/utils.py", line 222, in list_languages
    lang =  [f.split('.')[0] for f in os.listdir(cls._get_directory()) if f.endswith('.txt')]
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/stellar_base/wordlist'
```

I do see that the python3 module 'mnemonic' includes a Japanese and an English wordlist available at:

> /usr/local/lib/python3.6/site-packages/mnemonic/wordlist/english.txt

...but I'm not sure if it meets all requirements for use with Stellar - eg, there are some 3-character words in the list and I wasn't sure if there were any minimum length requirements for seed words of 4+ or 5+ characters.

If we can use the one provided in the mnemonic module, I'm not sure if it can be referenced by this module within python or if we just need to duplicate it.

There are 2048 words in the wordlist I found.  Is that enough "entropy" to be secure as a seed word list?  Would that be 2048^12?  2048^24?

**Comment by kfiresmith** [comment]
Copying the wordlist from the mnemonic module into .../stellar_base/wordlist/ seems to work (but it's a hack that we don't want anyone else to have to do...)
```python
Python 3.6.3 (default, Oct  9 2017, 12:07:10) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stellar_base.utils import StellarMnemonic
>>> sm = StellarMnemonic()
>>> m = sm.generate()
door mystery hurt universe bright attend palace embark rare badge affair grab
```

**Comment by overcat** [comment]
Please try installing from the latest code on Github. We [tested  it](https://github.com/StellarCN/py-stellar-base/blob/master/tests/test_utils.py#L56) on Python 2.7 / 3.4 / 3.5 and it worked fine.

You can follow here to install it.
```
git clone https://github.com/StellarCN/py-stellar-base.git
cd py-stellar-base
python setup.py install # may need root privileges
```

**Comment by kfiresmith** [comment]
Hi @overcat  - that's essentially what I did:
```
pip3 install ./py-stellar-base
```
Fedora 27 runs a pretty bleeding edge version of Python, but I can't imagine that has anything to do with the wordlist being missing:
```
Python 3.6.3 (default, Oct  9 2017, 12:07:10)
```

OK so this is interesting.  From the code at:  https://github.com/StellarCN/py-stellar-base/blob/8e1c4577674b46f84e30ea7852a2996d42fca02b/stellar_base/utils.py#L209
I think it's asking it to pull the default english wordlist as a built-in component of StellarMnemonic, but alas, no english wordlist exists at https://github.com/StellarCN/py-stellar-base/tree/master/stellar_base/wordlist

**Comment by kfiresmith** [comment]
What if we snagged: https://github.com/trezor/python-mnemonic/blob/master/mnemonic/wordlist/english.txt, and put it into https://github.com/StellarCN/py-stellar-base/tree/master/stellar_base/wordlist
?

**Comment by kfiresmith** [comment]
Same should be done for Japanese IMO

**Comment by kfiresmith** [comment]
I'm not sure how to link the pull request to the issue, but I made the changes to fix this here:  https://github.com/StellarCN/py-stellar-base/pull/59

Apologies I've never made a pull request before so I probably did it all wrong.

**Comment by kfiresmith** [comment]
It actually looks like more fundamentally there is a problem with the ../wordlist/.. folder not being installed during a pip install run pointing at a local copy of the git repo.  Please see:
```
(kfiresmithstellar) [root@localhost kfiresmithstellar]# pip3.6 install ./py-stellar-base
Processing ./py-stellar-base
Collecting ed25519 (from stellar-base==0.1.0)
  Using cached ed25519-1.4.tar.gz
Collecting crc16 (from stellar-base==0.1.0)
  Using cached crc16-0.1.1.zip
Collecting requests (from stellar-base==0.1.0)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting SSEClient (from stellar-base==0.1.0)
  Using cached sseclient-0.0.18.tar.gz
Collecting numpy (from stellar-base==0.1.0)
  Using cached numpy-1.13.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting toml (from stellar-base==0.1.0)
  Using cached toml-0.9.4.tar.gz
Collecting mnemonic (from stellar-base==0.1.0)
  Using cached mnemonic-0.18.tar.gz
Collecting urllib3<1.23,>=1.21.1 (from requests->stellar-base==0.1.0)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->stellar-base==0.1.0)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->stellar-base==0.1.0)
  Using cached certifi-2017.11.5-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->stellar-base==0.1.0)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting six (from SSEClient->stellar-base==0.1.0)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting pbkdf2 (from mnemonic->stellar-base==0.1.0)
  Using cached pbkdf2-1.3.tar.gz
Installing collected packages: ed25519, crc16, urllib3, idna, certifi, chardet, requests, six, SSEClient, numpy, toml, pbkdf2, mnemonic, stellar-base
  Running setup.py install for ed25519 ... done
  Running setup.py install for crc16 ... done
  Running setup.py install for SSEClient ... done
  Running setup.py install for toml ... done
  Running setup.py install for pbkdf2 ... done
  Running setup.py install for mnemonic ... done
  Running setup.py install for stellar-base ... done
Successfully installed SSEClient-0.0.18 certifi-2017.11.5 chardet-3.0.4 crc16-0.1.1 ed25519-1.4 idna-2.6 mnemonic-0.18 numpy-1.13.3 pbkdf2-1.3 requests-2.18.4 six-1.11.0 stellar-base-0.1.0 toml-0.9.4 urllib3-1.22
(kfiresmithstellar) [root@localhost kfiresmithstellar]# python3.6
Python 3.6.3 (default, Oct  9 2017, 12:07:10) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from stellar_base.utils import StellarMnemonic
>>> sm = StellarMnemonic()
>>> m = sm.generate()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/coinop/bin/stellarCN_sdk/kfiresmithstellar/lib64/python3.6/site-packages/stellar_base/utils.py", line 236, in generate
    ret = self.to_mnemonic(os.urandom(strength // 8))
  File "/home/coinop/bin/stellarCN_sdk/kfiresmithstellar/lib64/python3.6/site-packages/mnemonic/mnemonic.py", line 146, in to_mnemonic
    if self.detect_language(' '.join(result)) == 'japanese':  # Japanese must be joined by ideographic space.
  File "/home/coinop/bin/stellarCN_sdk/kfiresmithstellar/lib64/python3.6/site-packages/mnemonic/mnemonic.py", line 78, in detect_language
    languages = cls.list_languages()
  File "/home/coinop/bin/stellarCN_sdk/kfiresmithstellar/lib64/python3.6/site-packages/stellar_base/utils.py", line 222, in list_languages
    lang =  [f.split('.')[0] for f in os.listdir(cls._get_directory()) if f.endswith('.txt')]
FileNotFoundError: [Errno 2] No such file or directory: '/home/coinop/bin/stellarCN_sdk/kfiresmithstellar/lib64/python3.6/site-packages/stellar_base/wordlist'
```

**Comment by kfiresmith** [comment]
Oddly enough if you avoid a pip install and simply run 'python3.6 setup.py install', after a lot of verbose output, it successfully seems to install the wordlist folder.  
So it seems like there is a problem with pip3 doing an install from a local folder copy of the git repo, and I'm not sure how to fix that since I've never created a Python package.  Perhaps someone who creates those might know what would need to be changed in the repo to make the '/wordlist/' folder get installed?

**Comment by overcat** [comment]
please clone https://github.com/overcat/py-stellar-base.git , just check if it works for you and let me know.

**Comment by kfiresmith** [comment]
Thanks @overcat  - I can see now that regular python 'mnemonic' module is imported which provides 'english.txt' and 'japanese.txt', I've tested mnemonic seed generation on Python 3.6.3 and everything works as expected using your fork.  I hope it is going to be merged into master.  I have more testing problems to file against seed recovery which I'll do separately.

**Comment by overcat** [comment]
Thanks for your feedback, waiting for @manran to review the code.
