### ISSUE TITLE
async offers stream return 406 error

### ISSUE THREAD

**Issue by minherc** [StellarCN/py-stellar-base#588]
As I read in the documentation, everything seems to be supported:
https://stellar-sdk.readthedocs.io/en/stable/api.html?highlight=server.offers().for_seller().cursor#id9
There is almost no search for information on 406 errors in the SDK.
Thanks in advance for replies and advice.

ps: tried both on the local horizon server and on the main
code:
```
HORIZON_URL = "https://horizon.stellar.org"
async def offers(acc1):
    async with ServerAsync(HORIZON_URL, AiohttpClient()) as server:
        async for offers in server.offers().for_seller(acc1).cursor(cursor=last_cursor).stream():
            ofr2df(offers) ##  acc_offers
#            print(f"\nacc: {acc}\n offers len: {len(offers)}")
```
error: 

```
ConnectionError: fetch https://horizon.stellar.org/offers failed: 406
```
the function is called like this:
```
async def listen():
    global acc
    await asyncio.gather( 
    await asyncio.get_running_loop().run_in_executor(None, offers, acc[1])
    )
if __name__ == "__main__":
    asyncio.run(listen())
```
pps: sdk update 8.0 beta

**Comment by overcat** [comment]
I also encountered this error when I tried to test this stream point in [Stellar laboratory](https://laboratory.stellar.org/#explorer?resource=offers&endpoint=all&values=eyJzZWxsaW5nIjoibmF0aXZlIiwiYnV5aW5nIjoiQVFVQTpHQk5aSUxTVFZRWjRSN0lLUURHSFlHWTJRWEw1UU9GSllRTVhQS1dSUk01UEFWN1k0TTY3QVFVQSIsInN0cmVhbWluZyI6dHJ1ZSwiY3Vyc29yIjoibm93Iiwib3JkZXIiOiJkZXNjIn0%3D&network=public), I will give you a reply once I find the source of the problem, thanks.

**Comment by overcat** [comment]
https://github.com/stellar/go/issues/4348

**Comment by minherc** [comment]
Thank you very much for the quick response.
  Is this a bug in horizon server?

**Comment by overcat** [comment]
I'm currently not sure if the documentation is wrong, maybe the offers endpoint doesn't support streams, still waiting for a response from SDF, maybe you can try to use timed polling instead of stream.

**Comment by minherc** [comment]
Thanks a lot for your help. As far as I can see through the time poll, this will be a crooked decision, an extra load on the server.

ps fee_stats() in stream return 406 too
code:
```
async def comis_stat():
    async with ServerAsync(HORIZON_URL, AiohttpClient()) as server:
        async for stat in server.fee_stats().stream(): # cursor(cursor=last_cursor)
            comstat = stat ##  comis stat
            print(f"\comstat: {comstat}")
```

**Comment by overcat** [comment]
The fee state endpoint does not support stream, in general you also don't need to access this endpoint, you can learn how to set [base_fee here](https://developers.stellar.org/docs/glossary/fees/#surge-pricing).

**Comment by minherc** [comment]
Strange, it says that it supports
https://stellar-sdk.readthedocs.io/en/stable/api.html?highlight=fee_stats()#id6

**Comment by overcat** [comment]
It is inherited from the parent class. In fact, it does not support stream. I will improve it in the coming release, sorry for causing you trouble.
