### ISSUE TITLE
How to get a transaction NATIVE value?

### ISSUE THREAD

**Issue by vikujangid** [StellarCN/py-stellar-base#598]
In Pyhton library I didn't find any example code that shows the value/amount of a transaction. For example:

`https://horizon.stellar.org/accounts/GCR7DQSRAFZHOC7QHPRNI7G55ZHF2EC2QA7V44XSX26WOJEV2Q7S42EW/payments?order=desc`

There is transaction which has amount of `0.0000025`. I want this amount using Python code, but I don't know how. 

I tried with the following code but no success
`for tx in server.payments().for_account(account_id)._embedded():
    print (tx)`

**Comment by overcat** [comment]
Hope the following example helps:

```
from stellar_sdk import Server

server = Server(horizon_url="https://horizon.stellar.org")
account_id = "GCR7DQSRAFZHOC7QHPRNI7G55ZHF2EC2QA7V44XSX26WOJEV2Q7S42EW"
resp = server.payments().for_account(account_id).call()
for record in resp['_embedded']['records']:
    print(record)
```
