### ISSUE TITLE
429 status code

### ISSUE THREAD

**Issue by lexayat** [StellarCN/py-stellar-base#621]
Hello, I can not find the answer to the question.

How does sdk handle 429 status code? Looks like I can't wait for an answer.
https://developers.stellar.org/api/introduction/rate-limiting/

Thanks for the help.

**Comment by overcat** [comment]
Hi, if you encounter a 429 error, the SDK will throw a [BadRequestError](https://stellar-sdk.readthedocs.io/en/stable/api.html#badrequesterror) exception and `error.status == 429`

**Comment by lexayat** [comment]
@overcat Thank you
