### ISSUE TITLE
Transaction "tx_too_late"

### ISSUE THREAD

**Issue by rcaldas-com** [StellarCN/py-stellar-base#623]
To send a transaction I just used ".set_timeout(100)" 

I didn't use the network for a while and now I'm getting the error "tx_too_late"

Searching I saw about TimeBounds and tried the following commented lines:

```
transaction = (
    TransactionBuilder(
        source_account=server.load_account(issuer_kp.public_key),
        network_passphrase=network_passphrase
    )
    .append_payment_op(keypair.public_key, issuer.get_asset(), str(amount))
    # .set_timeout(100)
    # .add_time_bounds(0, 100)
    # .add_time_bounds(int(datetime.utcnow().timestamp()), int(datetime.utcnow().timestamp())+100)
    # .add_time_bounds(int(time()), int(time())+100)
    .build()
)
```

None of them worked, I keep getting "tx_too_late"
What am I doing wrong?

**Comment by overcat** [comment]
Can you check if the time on your local machine is correct?

**Comment by rcaldas-com** [comment]
> Can you check if the time on your local machine is correct?


Thank you!
I was running in container inside a cluster and the host that took the container was without ntp package and with a 2 minutes offset in time.

Installed `ntp` and checked with `ntpq -p` as [Debian NTP Docs](https://wiki.debian.org/NTP) suggests.

That fixed, returning to use only `set_timeout()`
