### ISSUE TITLE
Timebounds Warning Question

### ISSUE THREAD

**Issue by hbirkdale** [StellarCN/py-stellar-base#632]
Hi @overcat - thanks for the latest release. I have a question for you and would like your opinion.

We are just finishing upgrading the SDK from 5.0 to 8.1.  One of the breaking changes from 7.0 is the adding of a Warning to the logs when Timebounds are not set on a Transaction. We had no timebounds set on any of our transactions. 

I know the docs say to set timebounds - here's the quote:
`
If maxTime is 0, upper time bounds are not set. In this case, if a transaction does not make it to the transaction set, it is kept in memory and continuously tries to make it to the next transaction set. Because of this, we advise that all transactions are created with time bounds to invalidate transactions after a certain amount of time, especially if you plan to resubmit your transaction at a later time.`

https://developers.stellar.org/docs/fundamentals-and-concepts/stellar-data-structures/operations-and-transactions#transaction-attributes

I'm focusing on the words "..., especially if you plan to resubmit your transaction at a later time." We think this means "... resubmit your transaction at a later time _with a new sequence number_."  Our app will never do that - we keep retrying and increase fees if we need to - but we won't ever have a timeout.

I think our options are:
a. Use the add_time_bounds method in TransactionBuilder and set it with min=0 and max=0. According to the quote above "If maxTime is 0, upper time bounds are not set." 
b. Use the same method but set the maxTime to some LARGE number months or weeks out.

What are your thoughts? Have you seen anyone else in this situation?
Thanks for keeping the SDK up to date.
Hank

**Comment by overcat** [comment]
Hi @hbirkdale, you can now set time bounds to `TimeBounds(min_time=0, max_time=0)` if you didn't set timeBounds before, but used other means to ensure that your code works correctly.

> I'm focusing on the words "..., especially if you plan to resubmit your transaction at a later time." We think this means "... resubmit your transaction at a later time with a new sequence number." Our app will never do that - we keep retrying and increase fees if we need to - but we won't ever have a timeout.

If you are always guaranteed to use the same sequence number for the transaction, only one will eventually take effect, so you don't have to worry about an operation accidentally being executed twice.
