### ISSUE TITLE
server.offers.for_buying broken

### ISSUE THREAD

**Issue by usser0134** [StellarCN/py-stellar-base#647]
The output of  	server.offers().for_buying(asset) is totallly wrong
Price output is broken, amount output is broken

**Comment by overcat** [comment]
Sorry I can't reproduce this, here is an example and it works fine.

```
from stellar_sdk import Server, Asset

server = Server(horizon_url="https://horizon.stellar.org")

buying = Asset("USDC", "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN")
selling = Asset.native()
offers_data = server.offers().for_buying(buying).for_selling(selling).order(desc=True).call()
print(offers_data)
```

Would you mind providing your code?

**Comment by usser0134** [comment]
def GetAssetBuyOffersData(server, asset):
	offers_call_builder = (server.offers().for_buying(asset).limit(200))

	offers_records = []
	offers_records += offers_call_builder.call()["_embedded"]["records"]

	while page_records := offers_call_builder.next()["_embedded"]["records"]:
		offers_records += page_records

	return offers_records

**Comment by usser0134** [comment]
the there's a bug in laboratory too, because in horizon works.. i post the code in few mins

**Comment by overcat** [comment]
Can you post the url here if working in horizon? Thanks.

**Comment by usser0134** [comment]
nvm, you are right.. is not working even in horizon.. Strange, where should i report this issue?

**Comment by overcat** [comment]
Maybe you want to access trades instead of offers? https://developers.stellar.org/api/resources/trades/

For horizon, you can file an issue here: https://github.com/stellar/go

**Comment by usser0134** [comment]
One more question, to not open another topic..  How should we use new price class?  i dont get how it generates new price?

**Comment by overcat** [comment]
In Stellar, prices are stored in fractions, e.g. 0.5 would be stored as Price(1, 2), 0.12334 would be stored as Price(6167, 50000). 

Generally speaking, you don't need to pay too much attention to it, the SDK will automatically convert the "0.5" you passed in to Price object
