### ISSUE TITLE
RFE:  Create SEP-0005 reference implementation wallet in Python3

### ISSUE THREAD

**Issue by kfiresmith** [StellarCN/py-stellar-base#66]
## Request for Enhancement
Hello,
As @manran pointed out in #62, there is a general effort to add Key Derivation Methods for Stellar Accounts as covered in:  https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0005.md

Currently there is a reference implementation wallet in Go, NodeJS, and PHP.  We should endeavor to adapt the Go version for Python:
https://github.com/stellar/go/tree/master/tools/stellar-hd-wallet

This code could potentially replace the work done in this SDK for the current simple mnemonic word list seed generation functionality in this SDK, since full support for UTF-8 (eg Chinese) is supported in BIP-39:
https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#Wordlist

I also thing that test-case 4 of SEP-0005 should be targeted, "Mnemonic (24 words + BIP 39 passphrase)" - this is the ideal for security in my opinion.

**Comment by overcat** [comment]
I have completed this proposal, can you test it for me?
Please clone the code from here: https://github.com/overcat/py-stellar-base
If it works for you, I will merge it.
Thank you.

**Comment by kfiresmith** [comment]
Thanks very much @overcat  - I'm starting to examine and test now.  It may be a day or two before I have this completed.
