### ISSUE TITLE
docstrings

### ISSUE THREAD

**Issue by tempofr** [StellarCN/py-stellar-base#72]
We need better python docstrings...

At least for the builder and the address functions.. I propose we basically copy those from the javascript implementation which has beautiful docs.

http://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

**Comment by theaeolianmachine** [comment]
I just made a large pull request covering this and more in #87, so please take a look!

**Comment by overcat** [comment]
@theaeolianmachine Thank you very much! I will check it ASAP.
