### ISSUE TITLE
Soroban - authorization gives IndexError

### ISSUE THREAD

**Issue by yuriescl** [StellarCN/py-stellar-base#756]
```
File "/home/...", line 250, in sign_f
    authorization_entry: AuthorizationEntry = op.auth[0]
                                              ~~~~~~~^^^
IndexError: list index out of range
```

My code was taken from the example https://github.com/StellarCN/py-stellar-base/blob/a4ee387a373b6b3530f84e0bb5cf78dd9fa1c7e6/examples/soroban_auth_with_stellar_account.py#L50
```
def sign_f(tx):
        latest_ledger = state["soroban_server"].get_latest_ledger().sequence
        op = tx.transaction.operations[0]
        assert isinstance(op, InvokeHostFunction)
        authorization_entry: AuthorizationEntry = op.auth[0]
        authorization_entry.set_signature_expiration_ledger(latest_ledger + 3)
        authorization_entry.sign(signer_secret, state["network_passphrase"])
```

Is the example up to date with current Soroban authorization format?

**Comment by overcat** [comment]
I tested the example in the local repository and it ran correctly. The error you encountered might be because the function you called does not require an "auth" field?

**Comment by yuriescl** [comment]
> I tested the example in the local repository and it ran correctly. The error you encountered might be because the function you called does not require an "auth" field?

If your code ran successfully then I imagine it's an issue on my end. Do you have an example contract (Rust) and the caller (Python) I could have a look at? I'm not sure what is an `auth` field, couldn't find any mention of it, is it a recent addition?

**Comment by yuriescl** [comment]
This is the code I'm working on that's raising the error:
https://github.com/bp-ventures/lightecho-stellar-oracle/blob/95c827e6b40ff402835708c0feb5657b9f3f941e/oracle-onchain/v2/cli/cli.py#L349

When I call the `initialize()`, it goes through until it reaches that `authorization_entry: AuthorizationEntry = op.auth[0]` line, which raises the error.

There's an equivalent JS code that doesn't raise any errors and calls the same contract function (`initialize`):
https://github.com/bp-ventures/lightecho-stellar-oracle/blob/95c827e6b40ff402835708c0feb5657b9f3f941e/docs/v2.html#L210

Contract seems to be working fine with the JS code, so the issue appears to be somewhere in the Python code, maybe I missed something.

**Comment by yuriescl** [comment]
Thanks.
When calling the `assets()` function:
https://github.com/bp-ventures/lightecho-stellar-oracle/blob/95c827e6b40ff402835708c0feb5657b9f3f941e/oracle-onchain/v2/cli/cli.py#L375

I get this error:
```
File "/home/yuri/lightecho-stellar-oracle/oracle-onchain/v2/cli/cli.py", line 138, in invoke_contract_function
    tx_hash, tx_data = send_tx(tx, signer=signer)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/yuri/lightecho-stellar-oracle/oracle-onchain/v2/cli/cli.py", line 95, in send_tx
    tx = state["soroban_server"].prepare_transaction(tx)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/yuri/.cache/pypoetry/virtualenvs/cli-YsNgcThI-py3.11/lib/python3.11/site-packages/stellar_sdk/soroban/server.py", line 303, in prepare_transaction
    raise RequestException(None, resp.error)

stellar_sdk.soroban.exceptions.RequestException: <RequestException [code=None, message=HostError: Error(WasmVm, InternalError)
DebugInfo not available
]>
```

But the same function call works in the JS code:
https://github.com/bp-ventures/lightecho-stellar-oracle/blob/95c827e6b40ff402835708c0feb5657b9f3f941e/docs/v2.html#L223

**Comment by yuriescl** [comment]
Seems like a panic coming from the contract but I don't know how to see more details, apparently I need to set a debug flag or something.

**Comment by yuriescl** [comment]
Indeed, there's no need for `Stellar Account` authorization when calling `initialize`, this was a mistake on my end.
It's all working now, thank you for the elaborate response and testing.
