### ISSUE TITLE
Exception: have no sequence, maybe not funded?

### ISSUE THREAD

**Issue by HWUq** [StellarCN/py-stellar-base#76]
Hello,
I tried to send transaction from one account to another.
```
from stellar_base.builder import Builder
seed = "seed"
builder = Builder(secret=seed, network='public') 
bob_address = 'GBSNPTNJFNYOOPKRQE5VQTRVDP7F43RY4Z4OK4CNQWYCOL6QDCHCII57'
builder.append_payment_op(bob_address,'1','XLM')

builder.sign()
builder.submit()
```

But I got this error: "Exception: have no sequence, maybe not funded?"

**Comment by overcat** [comment]
It works well for me, maybe you should try again? It may be caused by a network error.

In addition, if the target address has not been activated, you need to activate it first.
```
from stellar_base.builder import Builder
seed = "seed"
builder = Builder(secret=seed, network='public') 
bob_address = 'GBSNPTNJFNYOOPKRQE5VQTRVDP7F43RY4Z4OK4CNQWYCOL6QDCHCII57'
builder.append_create_account_op(bob_address, 1)
builder.sign()
builder.submit()
```

**Comment by HWUq** [comment]
thanks for answer. But if I generate new address and I want to send Stellar to new address. How should I do it?

**Comment by overcat** [comment]
At first, you need to activate it.
```
from stellar_base.builder import Builder
seed = "seed"
builder = Builder(secret=seed, network='public') 
bob_address = 'YOUR_NEW_STELLAR_ADDRESS' 
builder.append_create_account_op(bob_address, 1)
builder.sign()
builder.submit()
```
Then you can send xlm to your new address.
```
from stellar_base.builder import Builder
seed = "seed"
builder = Builder(secret=seed, network='public') 
bob_address = 'YOUR_NEW_STELLAR_ADDRESS' 
builder.append_payment_op(bob_address,'100','XLM')
builder.sign()
builder.submit()
```

**Comment by HWUq** [comment]
Thanks, but...
Lets say some user generate address and wants to withdraw Stellar to new generate address. But address is not activated. And I dont have seed. How should I deal with that?

I tried with my own address and seed and I got this error "Exception: have no sequence, maybe not funded?"

**Comment by overcat** [comment]
```
seed = "THE_SECRET_KEY_OF_YOUR_OLD_ACCOUNT"
```
Are you sure you are using the correct seed? The seed is the secret key of your old account, if you want to withdraw xlm to a new address, you must provide the secret of your old account, if this seed is incorrect(for example, the account of the seed is not activated), you will get that error.

**Comment by overcat** [comment]
close until there is more information.
