### ISSUE TITLE
Add API to query ledger/transactions.

### ISSUE THREAD

**Issue by monohydroxy** [StellarCN/py-stellar-base#77]
For example, I'd like to use the Python API to make the following type of query:
    curl 'https://horizon-testnet.stellar.org/ledgers?cursor=&limit=1&order=desc'
And return the result data.
Once the ledger gives a transaction, I'd like to query the transaction in a similar fashion.

Is this possible?

**Comment by overcat** [comment]
Yes.
```
from stellar_base.horizon import Horizon
horizon = Horizon()
horizon.ledgers({ 'limit': 1, 'order': 'desc', 'cursor': '' })
```
Check [here](https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/horizon.py) for more detail.

Maybe we should write a document : -)

**Comment by monohydroxy** [comment]
Thank you!  That's what I'm looking for.  

Unfortunately, I'm getting different results with horizon.account_offers() than I see on StellarChain.io.

**Here is my code**
    h = Horizon(HORIZON_LIVE)
    params = { 'cursor': '' , 'limit': 10, 'order': 'desc' }
    q = h.account_offers(addr, params)
    pp = pprint.PrettyPrinter(depth=6)
    pp.pprint(q)

**Here is my output (only one offer):**
{u'_embedded': {u'records': [{u'_links': {u'offer_maker': {u'href': u'https://horizon.stellar.org/accounts/GBLO5U6ZLY5MMUH44XJUS3YU3ZI3UODTZPZWPDLWOOFBL5VWX74RTDXK'},
                                          u'self': {u'href': u'https://horizon.stellar.org/offers/673274'}},
                              u'amount': u'10.0000000',
                              u'buying': {u'asset_code': u'EQD',
                                          u'asset_issuer': u'GCGEQJR3E5BVMQYSNCHPO6NPP3KOT4VVZHIOLSRSNLE2GFY7EWVSLLTN',
                                          u'asset_type': u'credit_alphanum4'},
                              u'id': 673274,
                              u'paging_token': u'673274',
                              u'price': u'1000.0000000',
                              u'price_r': {u'd': 1, u'n': 1000},
                              u'seller': u'GBLO5U6ZLY5MMUH44XJUS3YU3ZI3UODTZPZWPDLWOOFBL5VWX74RTDXK',
                              u'selling': {u'asset_type': u'native'}}]},
 u'_links': {u'next': {u'href': u'https://horizon.stellar.org/accounts/GBLO5U6ZLY5MMUH44XJUS3YU3ZI3UODTZPZWPDLWOOFBL5VWX74RTDXK/offers?order=desc&limit=10&cursor=673274'},
             u'prev': {u'href': u'https://horizon.stellar.org/accounts/GBLO5U6ZLY5MMUH44XJUS3YU3ZI3UODTZPZWPDLWOOFBL5VWX74RTDXK/offers?order=asc&limit=10&cursor=673274'},
             u'self': {u'href': u'https://horizon.stellar.org/accounts/GBLO5U6ZLY5MMUH44XJUS3YU3ZI3UODTZPZWPDLWOOFBL5VWX74RTDXK/offers?order=desc&limit=10&cursor='}}}


When I look at this same address on StellarChain.io I get lots of offers:
https://stellarchain.io/address/GBLO5U6ZLY5MMUH44XJUS3YU3ZI3UODTZPZWPDLWOOFBL5VWX74RTDXK

Am I doing something wrong or misunderstanding something?

Thanks Again

-MH.

**Comment by overcat** [comment]
`h.account_offers(addr, params)` shows the offers that are still activity, it will not show up on this page if it has done or was canceled. You can check your offers from here: https://horizon.stellar.org/accounts/GBLO5U6ZLY5MMUH44XJUS3YU3ZI3UODTZPZWPDLWOOFBL5VWX74RTDXK/offers?order=desc&limit=10 , please check it.

Maybe you can try `account_effers()`, it can display more data, but you need to process your data.
https://horizon.stellar.org/accounts/GBLO5U6ZLY5MMUH44XJUS3YU3ZI3UODTZPZWPDLWOOFBL5VWX74RTDXK/effects?order=desc&limit=10

**Comment by overcat** [comment]
close until there is more information.
