### ISSUE TITLE
`parameters` should be optional when building a contract-invoking transaction

### ISSUE THREAD

**Issue by ElliotFriend** [StellarCN/py-stellar-base#788]
**Describe the bug**

When building a transaction to invoke a Soroban contract, using the `TransactionBuilder().append_invoke_contract_function_op(...)` method, the `parameters` parameter is required. I think it should be an optional parameter in this method.

Not all contract invocations require parameters. For example, the [`increment` example contract](https://github.com/stellar/soroban-examples/blob/7a7cc6268ada55113ce0b82a3ae4405f7ec8b8f0/increment/src/lib.rs#L12) doesn't take any parameters.

It seems like providing an empty list works, though:

```python
transaction = (
    TransactionBuilder(
        source_account,
        Network.FUTURENET_NETWORK_PASSPHRASE,
        base_fee=100,
    )
    .append_invoke_contract_function_op(
        contract_id=contract_address,
        function_name="increment",
        parameters=[],
    )
    .set_timeout(30)
    .build()
)
```

**What version of dependencies are you using?**

```text
annotated-types==0.5.0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
idna==3.4
mnemonic==0.20
pycparser==2.21
pydantic==2.3.0
pydantic_core==2.6.3
PyNaCl==1.5.0
requests==2.31.0
six==1.16.0
stellar-base-sseclient==0.0.21
stellar-sdk @ git+https://github.com/StellarCN/py-stellar-base.git@5a3e556aa868f80bded507e7b26fd8973d3f63cf
toml==0.10.2
typing_extensions==4.8.0
urllib3==2.0.5
xdrlib3==0.1.1
```

**To Reproduce**

If I leave out `parameters` altogether, like this:

```python
transaction = (
    TransactionBuilder(
        source_account,
        Network.FUTURENET_NETWORK_PASSPHRASE,
        base_fee=100,
    )
    .append_invoke_contract_function_op(
        contract_id=contract_address,
        function_name="increment",
    )
    .set_timeout(30)
    .build()
)
```

I receive the following error when running my script:

```bash
$ ./build-transaction.py
Traceback (most recent call last):
  File "/Users/elliotvoris/Dev/soroban/random-scripts/./build-transaction.py", line 21, in <module>
    .append_invoke_contract_function_op(
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TransactionBuilder.append_invoke_contract_function_op() missing 1 required positional argument: 'parameters'
```

**Expected behavior**

I think it would help the ergonomics of using the SDK if the `parameters` were optional in this method.

**Additional context**

I'm working on some example Stellar transaction scripts for the `soroban-docs` site, and was using the `increment` example just for the simplicity of use. I'm sure there are other common contract functions that don't require parameters, too.

**Comment by overcat** [comment]
Thank you for your feedback, let us optimize it in the next release. Currently, you can solve this problem by passing an empty list.
