### ISSUE TITLE
Feature Request: Add helper functions to create SCAddress instance

### ISSUE THREAD

**Issue by yuriescl** [StellarCN/py-stellar-base#836]
**Is your feature request related to a problem? Please describe.**

I couldn't find a way to easily create instances of `SCAddress` from a pubkey (string).

To create an instance of `SCAddress`, it's necessary to provide either a `AccountID` or `Hash`:
```
class SCAddress:
    def __init__( 
        self,            
        type: SCAddressType,
        account_id: AccountID = None,  
        contract_id: Hash = None,  
    ) -> None:   
        self.type = type    
        self.account_id = account_id   
        self.contract_id = contract_id
```

But to obtain an instance of `AccountID`, it's necessary to provide a `PublicKey`:
```
class AccountID:     
    def __init__(self, account_id: PublicKey) -> None:    
        self.account_id = account_id
```

And to obtain a `PublicKey`, it's necessary to provide a `Uint256` value:
```
class PublicKey:   
    def __init__( 
        self, 
        type: PublicKeyType, 
        ed25519: Uint256 = None, 
    ) -> None:                             
        self.type = type
        self.ed25519 = ed25519
```

So to create an instance of `SCAddress` at the moment, apparently I need to:
```
sc_address = SCAddress(type, AccountID(PublicKey(public_key_type, Uint256(...)))
```
Which is a bit overwhelming.

**Describe the solution you'd like**

It would be great to have something like `address = SCAddress.from_account_id(pubkey_str)`, and `contract = SCAddress.from_contract_id(contract_address_str)`.

**Describe alternatives you've considered**

Described above.

**Comment by overcat** [comment]
I think it already exists.
```py
from stellar_sdk import Address, Keypair, scval

public_key = Keypair.random().public_key  # can be contract id (C...)
addr = Address(public_key)
sc_addr = addr.to_xdr_sc_address()
# or
sc_addr2 = scval.to_address(public_key).address
# assert sc_addr == sc_addr2

```
