### ISSUE TITLE
custom node 

### ISSUE THREAD

**Issue by upggr** [StellarCN/py-stellar-base#86]
Is it possible to use a custom node rather than "livenet" or "testnet" ?

**Comment by upggr** [comment]
or to make it more specific, allow change of the : 

HORIZON_LIVE = "https://horizon.stellar.org"
HORIZON_TEST = "https://horizon-testnet.stellar.org"

in the py-stellar-base/stellar_base/horizon.py  from the network variable

**Comment by overcat** [comment]
If you want to use a custom node, please follow my step.
```
from stellar_base.horizon import Horizon
horizon = Horizon('https://api.chinastellar.com')
```
