### ISSUE TITLE
Stream not successful transactions from horison 

### ISSUE THREAD

**Issue by mikheillomidze** [StellarCN/py-stellar-base#864]
How can I stream not successful transactions from horison? 

```python
from stellar_sdk import Server

server = Server(horizon_url="https://horizon-testnet.stellar.org")
account_id = "GASOCNHNNLYFNMDJYQ3XFMI7BYHIOCFW3GJEOWRPEGK2TDPGTG2E5EDW"
last_cursor = 'now'  # or load where you left off


def tx_handler(tx_response):
    print(tx_response)


for tx in server.transactions().for_account(account_id).cursor(last_cursor).stream():
    tx_handler(tx)
    
```

From this example, I am getting only successful transactions.

**Comment by overcat** [comment]
You can get all transactions by adding `.include_failed(True)`

https://stellar-sdk.readthedocs.io/en/stable/api.html#stellar_sdk.call_builder.call_builder_sync.OperationsCallBuilder.include_failed

**Comment by mikheillomidze** [comment]
> You can get all transactions by adding `.include_failed(True)`
> 
> https://stellar-sdk.readthedocs.io/en/stable/api.html#stellar_sdk.call_builder.call_builder_sync.OperationsCallBuilder.include_failed

Great! Thank you so much! <3
