### ISSUE TITLE
Add helper to [de]serialize `Keypair`

### ISSUE THREAD

**Issue by tupui** [StellarCN/py-stellar-base#900]
**Is your feature request related to a problem? Please describe.**

The Soroban CLI allows is reading/writing toml files to handle keys. Would you consider adding a `load/dump` API on the `Keypair` class? Similarly, it would be convenient to have that for config like the network definition.

**Describe the solution you'd like**

E.g. when creating a new `Keypair` it could internally write the secret key to file. I use the following to automatically save the key so that I don't lose it by accident if I automate things with a script for e.g.

```python
import tomli_w  # recommended from Python's doc

with open(f"source_account.toml", "wb") as fd:
    tomli_w.dump({"secret_key": new_account.secret}, fd)
```

**Comment by overcat** [comment]
Some users like to use TOML, some users prefer JSON, and there are even users who like to use YAML. And this part of the logic is particularly simple, I tend to let users implement it according to their own needs.

In addition, you may be interested in this topic: https://github.com/stellar/stellar-protocol/issues/198

**Comment by tupui** [comment]
Thanks for the share.

I am not sure I get all the opposing arguments. Having a key written in a file is not an issue per-se. Like we have SSH public and private files, GPG keys, etc. So using a standard way to write this file does not seem to be farfetched or abnormal.

I agree that without standard, it's difficult to say which format would be the best. Here I propose TOML as it's what Soroban does. Also I personally don't like to print to screen secrets. To many attack vectors there, to start with, a colleague watching your screen behind your back 😅 

Feel free to close 😃

**Comment by overcat** [comment]
For SSH Private Key and GPG Keys, we at least have a passphrase to add extra protection. If the purpose of soroban cli is for the mainnet, rather than for testing, perhaps similar protections should also be added.

**Comment by tupui** [comment]
Good point 👍 I asked on Discord 😃

**Comment by overcat** [comment]
Further discussions can be found at https://github.com/stellar/soroban-cli/issues/1255
