### ISSUE TITLE
How do I get contract balance from contract data in python sdk?

### ISSUE THREAD

**Issue by mwrrlvkixj** [StellarCN/py-stellar-base#945]
If you want to get programming help, I suggest you check out our 
[developer documentation](https://stellar-sdk.readthedocs.org/) and [examples](https://github.com/StellarCN/py-stellar-base/tree/master/examples) first. After that, if your problem 
is still not resolved, you can ask questions here 
or in [Stellar Stack Exchange](https://stellar.stackexchange.com).

Hi, does anyone know how to get contract balance from contract data in python sdk? I'm looking for the equivalent of [this](https://github.com/stellar/stellar-etl/blob/master/internal/transform/contract_data.go#L270) in python sdk.

**Comment by overcat** [comment]
Resolved the issue in a private conversation.
