### ISSUE TITLE
xdrlib.Error: array length too long for data.operations

### ISSUE THREAD

**Issue by jethdeguzman** [StellarCN/py-stellar-base#95]
What's the reason for limiting the number of operations to 100 in a transaction?

**Comment by overcat** [comment]
Please see https://www.stellar.org/developers/guides/concepts/transactions.html
> List of operations
Transactions contain an arbitrary list of operations inside them. Typically there is just one operation, but it’s possible to have multiple (up to 100). Operations are executed in order as one ACID transaction, meaning that either all operations are applied or none are. If any operation fails, the whole transaction fails. If operations are on accounts other than the source account, then they require signatures of the accounts in question.

**Comment by jethdeguzman** [comment]
Alright, thanks!
