### ISSUE TITLE
XDR parser bug

### ISSUE THREAD

**Issue by nikita-gorodeckij** [StellarCN/py-stellar-base#953]
https://github.com/StellarCN/py-stellar-base/blob/910367340b837dceab30ef46baf2b75ebd09fda4/stellar_sdk/fee_bump_transaction.py#L96

What the reason to add 1?
Looks like this line broke `FeeBumpTransactionEnvelope` parsing

For example, I can't parse transaction `39f0e146cdc79f03648a0619f049210773ea1d823b47de3dcfd4579700af82d4` and get error `ValueError: Invalid `base_fee`, it should be at least 34173299 stroops.` because of `base_fee` passed into constructor is `17091649` instead of `34183298`

**Comment by overcat** [comment]
I deeply apologize for any inconvenience caused to you. I will release a new version tomorrow to fix it.

**Comment by overcat** [comment]
Thank you for reporting this issue, we have fixed it in the latest version. https://github.com/StellarCN/py-stellar-base/releases/tag/11.0.0
