### ISSUE TITLE
Horizon v2.31.0 and RPC v21.4.0 changes

### ISSUE THREAD

**Issue by Shaptic** [StellarCN/py-stellar-base#958]
Please add support to your SDK for the following API changes.

## Horizon Changes
[Horizon v2.31.0](https://github.com/stellar/go/releases/tag/horizon-v2.31.0) made the following changes:

* **New endpoint**: `POST /transactions_async` allows asynchronous transaction submission (code: [stellar/go#5188](https://github.com/stellar/go/pull/5188)).
* **Error schema change**: `POST /transactions` now includes a the `hash` in its timeout response, which may or may not require code changes depending on how your SDK handles transaction submission errors (code: [stellar/go#5328](https://github.com/stellar/go/pull/5328)).

## Soroban RPC Changes

[RPC v21.4.0](https://github.com/stellar/soroban-rpc/releases/tag/v21.4.0) added the following endpoints:

* `getTransactions`, which returns pages of transaction details (code: [stellar/soroban-rpc#174](https://github.com/stellar/soroban-rpc/pull/174)).
* `getFeeStats`, which returns aggregated fee statistics over a few ledgers (code: [stellar/soroban-rpc#172](https://github.com/stellar/soroban-rpc/pull/172)).
* `getVersionInfo`, which returns detailed information about the software versions the RPC server is running (code: [stellar/soroban-rpc#132](https://github.com/stellar/soroban-rpc/pull/132)). Please keep in mind that this endpoint accidentally used `snake_case` for response fields and it will be updated to `camelCase` (see [soroban-rpc#164](https://github.com/stellar/soroban-rpc/pull/164)) as part of Protocol 22's breaking changes when the time comes.

## Reference

 * RPC documentation for [`getFeeStats`](https://developers.stellar.org/docs/data/rpc/api-reference/methods/getFeeStats).
 * RPC documentation for [`getTransactions`](https://developers.stellar.org/docs/data/rpc/api-reference/methods/getTransactions).
 * RPC documentation for [`getVersionInfo`](https://developers.stellar.org/docs/data/rpc/api-reference/methods/getVersionInfo).
 * Horizon documentation for [`/async_transactions`](https://developers.stellar.org/docs/data/horizon/api-reference/resources/submit-async-transaction).
 * JavaScript implementations: [stellar-sdk#989](https://github.com/stellar/js-stellar-sdk/pull/989) (`/transactions_async`) and [stellar-sdk#1006](https://github.com/stellar/js-stellar-sdk/pull/1006) (`/getFeeStats`), both included in [v12.2.0](https://github.com/stellar/js-stellar-sdk/releases/tag/v12.2.0).

**Comment by overcat** [comment]
The getVersionInfo interface has not been implemented yet, and we plan to wait until the breaking change is applied before adding it. Other interfaces have been implemented.
