### ISSUE TITLE
Inconsistent type in Address

### ISSUE THREAD

**Issue by suranap** [StellarCN/py-stellar-base#96]
[The documentation for Address](https://stellar-base.readthedocs.io/en/latest/api.html#address) says one should pass in a Horizon object in the `__init__`, but it fails at `get()` because [this line](https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/horizon.py#L60)  tries to append a string to a Horizon object. In fact, the Horizon object gets wrapped by another Horizon object [here](https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/address.py#L30). 

I'd prefer to pass in a Horizon object rather than a string. For now it seems the types and docs are inconsistent.

**Comment by overcat** [comment]
Thank you.
