### ISSUE TITLE
Protocol 22 Changes

### ISSUE THREAD

**Issue by aditya1702** [StellarCN/py-stellar-base#983]
# Protocol 22

## XDR Changes
- Added new XDR support for Soroban constructors which allows a contract to run custom initialization logic atomically when it's first created. You can read more about this change in [CAP-58](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0058.md). The following changes are introduced:
  - A new special contract function `__constructor` that may only be called by the Soroban host environment. The environment will call `__constructor` function if and only if the contract is being created from a Wasm exporting that function.
  - Introduce a new host function `create_contract_with_constructor` in Soroban environment that allows constracts to instantiate other contracts with constructors.
  - Introduce a new `HostFunction` XDR variant `HOST_FUNCTION_TYPE_CREATE_CONTRACT_V2` that acts in the same way as `HOST_FUNCTION_TYPE_CREATE_CONTRACT`, but also allows users to specify the constructor arguments.
  - Introduce a new `SorobanAuthorizedFunction` XDR variant `SOROBAN_AUTHORIZED_FUNCTION_TYPE_CREATE_CONTRACT_V2_HOST_FN` that allows users to sign the authorization payload corresponding to `HOST_FUNCTION_TYPE_CREATE_CONTRACT_V2` host function calls.

### Breaking Changes
- Changed `ErrorResultXDR` field naming from camelcase to snakecase - `error_result_xdr` - for `transactions_async` endpoint. ([#5445](https://github.com/stellar/go/pull/5445))
- The following deprecated fields have been removed ([#5478](https://github.com/stellar/go/pull/5478)):
  - `/asset`: `num_accounts` and `amount` [fields](https://github.com/stellar/go/blob/dfabe31b5b89cb235e81732d708a3f5bdeff507a/protocols/horizon/main.go#L180-L187)
  - `/transactions/:id`: `valid_before` and `valid_after` [fields](https://github.com/stellar/go/blob/dfabe31b5b89cb235e81732d708a3f5bdeff507a/protocols/horizon/main.go#L536-L538)

### Breaking Changes
- `createdAt` field in `getTransaction` response is now encoded as `string` instead of `int64`. ([#251](https://github.com/stellar/soroban-rpc/pull/251))
- The fields in `getVersionInfo` response were changed to Camel-case naming ([#164](https://github.com/stellar/soroban-rpc/pull/164)):
  - `commitHash`
  - `buildTimestamp`
  - `captiveCoreVersion`
  - `protocolVersion`
- The legacy `cost` field has been removed from `simulateTransaction` response. ([#295](https://github.com/stellar/soroban-rpc/pull/295)):
    - The correct resource costs can now be retrieved from the `transactionData` XDR in the response.
- Remove `pagingToken` from `getEvents` response and replace it with `cursor`. ([#297](https://github.com/stellar/soroban-rpc/pull/297))
  - Instead of being present in all event objects, the `cursor` will be at the top level of the response similar to `getTransactions`. This makes it easier to use and brings it in sync with how Cursor is used in other RPC endpoints
- Deprecated `getLedgerEntry` endpoint is now removed. ([#276](https://github.com/stellar/soroban-rpc/pull/276))
  - Users can use the more powerful `getLedgerEntries` endpoint to get the same result.

### Non-Breaking Changes
- Add transaction hash field - `txHash` - to `getTransactions` and `getTransaction` response. ([#299](https://github.com/stellar/soroban-rpc/pull/299), [#314](https://github.com/stellar/soroban-rpc/pull/314))
  - Each transaction object in the response now also includes a hex-encoded transaction hash string.

## SDF Reference Implementations
* [JavaScript](https://github.com/stellar/js-stellar-sdk/releases/tag/v13.0.0-beta.1) 
* [Java](https://github.com/stellar/java-stellar-anchor-sdk/releases/tag/2.11.0)

**Comment by overcat** [comment]
Included in https://pypi.org/project/stellar-sdk/12.0.0b0/
